<a href="https://colab.research.google.com/github/Samriddhi330/Assam-Flood-DSS/blob/main/01_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import os
import pandas as pd

# 1. Download CivicDataLab repository if not present
repo_path = 'flood-data-ecosystem-Assam'
if not os.path.exists(repo_path):
    print("Downloading CivicDataLab repository into Colab...\n")
    !git clone https://github.com/CivicDataLab/flood-data-ecosystem-Assam.git

# 2. Path to master dataset
dataset_path = 'flood-data-ecosystem-Assam/Sources/MASTER_VARIABLES.csv'

# 3. Read dataset
df = pd.read_csv(dataset_path)

print(f"✅ STEP 1 COMPLETE: Raw dataset loaded successfully!")
print(f"Total Rows: {df.shape[0]} | Total Columns: {df.shape[1]}\n")

print("--- FIRST 5 ROWS OF RAW DATA ---")
display(df.head())

print("\n--- RAW DATASET INFO & STRUCTURE ---")
df.info()

✅ STEP 1 COMPLETE: Raw dataset loaded successfully!
Total Rows: 11160 | Total Columns: 85

--- FIRST 5 ROWS OF RAW DATA ---

,object_id,district,rc_area,timeperiod,total_tender_awarded_value,erosion_tenders_awarded_value,SOPD_tenders_awarded_value,SDRF_sanctions_awarded_value,SDRF_tenders_awarded_value,RIDF_tenders_awarded_value,...,dtname,dtcode11,net_sown_area_in_hac,avg_electricity,avg_tele,rc_piped_hhds_pct,rc_nosanitation_hhds_pct,total_hhd,distance_from_river,drainage_density
0,18-300-00101,KOKRAJHAR,1069,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,KOKRAJHAR,18-300,32583.05,6.103794,2.0,0.947538,20.156822,62460.0,1718.766638,0.000542
1,18-300-00101,KOKRAJHAR,1069,2021_05,0.0,0.0,0.0,0.0,0.0,0.0,...,KOKRAJHAR,18-300,32583.05,6.103794,2.0,0.947538,20.156822,62460.0,1718.766638,0.000542
2,18-300-00101,KOKRAJHAR,1069,2021_06,0.0,0.0,0.0,0.0,0.0,0.0,...,KOKRAJHAR,18-300,32583.05,6.103794,2.0,0.947538,20.156822,62460.0,1718.766638,0.000542
3,18-300-00101,KOKRAJHAR,1069,2021_07,0.0,0.0,0.0,0.0,0.0,0.0,...,KOKRAJHAR,18-300,32583.05,6.103794,2.0,0.947538,20.156822,62460.0,1718.766638,0.000542
4,18-300-00101,KOKRAJHAR,1069,2021_08,0.0,0.0,0.0,0.0,0.0,0.0,...,KOKRAJHAR,18-300,32583.05,6.103794,2.0,0.947538,20.156822,62460.0,1718.766638,0.000542

--- RAW DATASET INFO & STRUCTURE ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11160 entries, 0 to 11159
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   object_id                                     11160 non-null  object
 1   district                                      11160 non-null  object
 2   rc_area                                       11160 non-null  int64
 3   timeperiod                                    11160 non-null  object
 4   total_tender_awarded_value                    11160 non-null  float64
 5   erosion_tenders_awarded_value                 11160 non-null  float64
 6   SOPD_tenders_awarded_value                    11160 non-null  float64
 7   SDRF_sanctions_awarded_value                  11160 non-null  float64
 8   SDRF_tenders_awarded_value                    11160 non-null  float64
 9   RIDF_tenders_awarded_value                    11160 non-null  float64
 10  LTIF_tenders_awarded_value                    11160 non-null  float64
 11  CIDF_tenders_awarded_value                    11160 non-null  float64
 12  Preparedness Measures_tenders_awarded_value   11160 non-null  float64
 13  Immediate Measures_tenders_awarded_value      11160 non-null  float64
 14  Others_tenders_awarded_value                  11160 non-null  float64
 15  Repair and Restoration_tenders_awarded_value  11160 non-null  float64
 16  Total_Animal_Washed_Away                      11160 non-null  float64
 17  Total_Animal_Affected                         11160 non-null  float64
 18  Population_affected_Total                     11160 non-null  float64
 19  Crop_Area                                     11160 non-null  float64
 20  Male_Camp                                     11160 non-null  float64
 21  Female_Camp                                   11160 non-null  float64
 22  Children_Camp                                 11160 non-null  float64
 23  Total_House_Fully_Damaged                     11160 non-null  float64
 24  Human_Live_Lost                               11160 non-null  int64
 25  Human_Live_Lost_Children                      11160 non-null  float64
 26  Human_Live_Lost_Female                        11160 non-null  float64
 27  Human_Live_Lost_Male                          11160 non-null  float64
 28  Embankments affected                          11160 non-null  float64
 29  Roads                                         11160 non-null  float64
 30  Bridge                                        11160 non-null  float64
 31  Embankment breached                           11160 non-null  float64
 32  max_rain                                      11160 non-null  float64
 33  mean_rain                                     11160 non-null  float64
 34  sum_rain                                      11160 non-null  float64
 35  mean_ndvi                                     11160 non-null  float64
 36  mean_ndbi                                     11160 non-null  float64
 37  count                                         11160 non-null  float64
 38  inundation_pct                                11160 non-null  float64
 39  inundation_intensity_mean                     11160 non-null  float64
 40  inundation_intensity_mean_nonzero             11160 non-null  float64
 41  inundation_intensity_sum                      11160 non-null  float64
 42  riverlevel_mean                               11160 non-null  float64
 43  riverlevel_min                                11160 non-null  float64
 44  riverlevel_max                                11160 non-null  float64
 45  total_expenditure_value                       11160 non-null  float64
 46  SDRF_expenditure_value                        11160 non-null  float64
 47  Immediate Measures_expenditure_value          11160 non-null  float64
 48  Others_expenditure_value                      11160 non-null  float64
 49  Repair and Restoration_expenditure_value      11160 non-null  float64
 50  Relief Camps                                  11160 non-null  float64
 51  Relief Centers                                11160 non-null  float64
 52  Relief Inmates                                11160 non-null  float64
 53  Relief_Camp_inmates                           11160 non-null  int64
 54  mean_sex_ratio                                11160 non-null  float64
 55  sum_aged_population                           11160 non-null  float64
 56  sum_young_population                          11160 non-null  float64
 57  sum_population                                11160 non-null  float64
 58  water                                         11160 non-null  float64
 59  trees                                         11160 non-null  float64
 60  flooded_vegetation                            11160 non-null  float64
 61  crops                                         11160 non-null  float64
 62  built_area                                    11160 non-null  float64
 63  bare_ground                                   11160 non-null  float64
 64  clouds                                        11160 non-null  float64
 65  rangeland                                     11160 non-null  float64
 66  schools_count                                 11160 non-null  int64
 67  health_centres_count                          11160 non-null  int64
 68  rail_length                                   11160 non-null  float64
 69  rail_count                                    11160 non-null  float64
 70  road_length                                   11160 non-null  float64
 71  mean_cn                                       11160 non-null  float64
 72  elevation_mean                                11160 non-null  float64
 73  slope_mean                                    11160 non-null  float64
 74  revenue_ci                                    11160 non-null  object
 75  dtname                                        11160 non-null  object
 76  dtcode11                                      11160 non-null  object
 77  net_sown_area_in_hac                          11160 non-null  float64
 78  avg_electricity                               11160 non-null  float64
 79  avg_tele                                      11160 non-null  float64
 80  rc_piped_hhds_pct                             11160 non-null  float64
 81  rc_nosanitation_hhds_pct                      11160 non-null  float64
 82  total_hhd                                     11160 non-null  float64
 83  distance_from_river                           11160 non-null  float64
 84  drainage_density                              11160 non-null  float64
dtypes: float64(74), int64(5), object(6)
memory usage: 7.2+ MB

In [6]:
# 1. Define essential columns for ML modeling
selected_columns = [
    'object_id', 'district', 'revenue_ci', 'timeperiod',
    # Hazard (XH)
    'sum_rain', 'max_rain', 'riverlevel_mean', 'distance_from_river', 'inundation_pct',
    # Exposure (XE)
    'sum_population', 'total_hhd', 'Crop_Area',
    # Vulnerability (XV)
    'road_length', 'health_centres_count', 'elevation_mean', 'slope_mean',
    # Raw Target
    'Population_affected_Total'
]

# 2. Filter dataset
df_clean = df[selected_columns].copy()

# 3. Calculate Target Variable: Affected Population Ratio (Y)
# Formula: Population_affected_Total / (sum_population + 1), bounded between 0 and 1
df_clean['affected_pop_ratio'] = (df_clean['Population_affected_Total'] / (df_clean['sum_population'] + 1)).clip(0, 1)

print(f"✅ STEP 2 COMPLETE: Selected 16 essential columns & calculated target variable!")
print(f"New Shape: {df_clean.shape[0]} Rows × {df_clean.shape[1]} Columns\n")

print("--- FIRST 5 ROWS OF SELECTED DATASET ---")
display(df_clean.head())

print("\n--- SELECTED DATASET INFO & STRUCTURE ---")
df_clean.info()

✅ STEP 2 COMPLETE: Selected 16 essential columns & calculated target variable!
New Shape: 11160 Rows × 18 Columns

--- FIRST 5 ROWS OF SELECTED DATASET ---

,object_id,district,revenue_ci,timeperiod,sum_rain,max_rain,riverlevel_mean,distance_from_river,inundation_pct,sum_population,total_hhd,Crop_Area,road_length,health_centres_count,elevation_mean,slope_mean,Population_affected_Total,affected_pop_ratio
0,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_04,166.249990,0.214262,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
1,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_05,300.919378,0.344883,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
2,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_06,914.725700,1.346394,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
3,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_07,788.617197,0.975052,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
4,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_08,795.942200,1.308983,0.0,1718.766638,0.005049,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0

--- SELECTED DATASET INFO & STRUCTURE ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11160 entries, 0 to 11159
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   object_id                  11160 non-null  object
 1   district                   11160 non-null  object
 2   revenue_ci                 11160 non-null  object
 3   timeperiod                 11160 non-null  object
 4   sum_rain                   11160 non-null  float64
 5   max_rain                   11160 non-null  float64
 6   riverlevel_mean            11160 non-null  float64
 7   distance_from_river        11160 non-null  float64
 8   inundation_pct             11160 non-null  float64
 9   sum_population             11160 non-null  float64
 10  total_hhd                  11160 non-null  float64
 11  Crop_Area                  11160 non-null  float64
 12  road_length                11160 non-null  float64
 13  health_centres_count       11160 non-null  int64
 14  elevation_mean             11160 non-null  float64
 15  slope_mean                 11160 non-null  float64
 16  Population_affected_Total  11160 non-null  float64
 17  affected_pop_ratio         11160 non-null  float64
dtypes: float64(13), int64(1), object(4)
memory usage: 1.5+ MB

In [7]:
import numpy as np

print("--- 1. MISSING (NULL) VALUE COUNT PER COLUMN ---")
nulls = df_clean.isnull().sum()
print(nulls)

print("\n--- 2. STATISTICAL SUMMARY OF NUMERICAL FEATURES ---")
display(df_clean.describe())

# Handle any missing or infinite values
num_cols = df_clean.select_dtypes(include=[np.number]).columns
df_clean[num_cols] = df_clean[num_cols].replace([np.inf, -np.inf], np.nan)
df_clean[num_cols] = df_clean[num_cols].fillna(df_clean[num_cols].median())

# Ensure physical values are non-negative
df_clean['sum_rain'] = df_clean['sum_rain'].clip(lower=0)
df_clean['max_rain'] = df_clean['max_rain'].clip(lower=0)
df_clean['sum_population'] = df_clean['sum_population'].clip(lower=0)
df_clean['distance_from_river'] = df_clean['distance_from_river'].clip(lower=0)

print("\n✅ STEP 3 COMPLETE: Missing values & physical bounds verified!")

--- 1. MISSING (NULL) VALUE COUNT PER COLUMN ---
object_id                    0
district                     0
revenue_ci                   0
timeperiod                   0
sum_rain                     0
max_rain                     0
riverlevel_mean              0
distance_from_river          0
inundation_pct               0
sum_population               0
total_hhd                    0
Crop_Area                    0
road_length                  0
health_centres_count         0
elevation_mean               0
slope_mean                   0
Population_affected_Total    0
affected_pop_ratio           0
dtype: int64

--- 2. STATISTICAL SUMMARY OF NUMERICAL FEATURES ---

,sum_rain,max_rain,riverlevel_mean,distance_from_river,inundation_pct,sum_population,total_hhd,Crop_Area,road_length,health_centres_count,elevation_mean,slope_mean,Population_affected_Total,affected_pop_ratio
count,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000,11160.000000
mean,103.037791,0.329178,11.225171,3314.734041,0.014976,200416.285275,43846.600000,70.309305,140958.591608,21.805556,98.601783,83.913692,1765.417025,0.007586
std,159.684955,0.362088,35.552493,3021.348254,0.054873,136671.304638,34724.332153,564.095966,91867.520268,14.329361,104.203418,3.813963,17140.632595,0.058435
min,0.000000,0.000000,0.000000,379.126625,0.000000,147.727197,0.000000,0.000000,0.123414,1.000000,19.313229,70.421100,0.000000,0.000000
25%,4.450470,0.035741,0.000000,1328.473449,0.000000,106905.579687,21471.000000,0.000000,75425.660036,9.750000,50.694877,82.918121,0.000000,0.000000
50%,42.849843,0.240279,0.000000,2327.260688,0.000000,174818.996875,38531.000000,0.000000,140069.712460,21.000000,72.594048,84.805387,0.000000,0.000000
75%,134.581803,0.496053,0.000000,4050.430116,0.000000,270639.153125,56887.500000,0.000000,185180.928129,33.250000,103.302705,86.054582,0.000000,0.000000
max,2113.367071,2.780199,508.346495,18894.999447,0.610256,771952.975000,257725.000000,18983.000000,457480.754254,71.000000,814.182769,89.949896,725306.000000,1.000000

✅ STEP 3 COMPLETE: Missing values & physical bounds verified!

In [8]:
# Save final dataset locally in Colab
df_clean.to_csv('master_dataset.csv', index=False)

print(f"✅ STEP 4 COMPLETE: Final dataset saved as 'master_dataset.csv'!")
print(f"Final File Shape: {df_clean.shape[0]} Rows × {df_clean.shape[1]} Columns\n")

print("--- FINAL CLEAN DATASET PREVIEW (FIRST 5 ROWS) ---")
display(df_clean.head())

print("\n--- FINAL COLUMN NAMES LIST ---")
for idx, col in enumerate(df_clean.columns):
    print(f"Column {idx+1}: {col}")

✅ STEP 4 COMPLETE: Final dataset saved as 'master_dataset.csv'!
Final File Shape: 11160 Rows × 18 Columns

--- FINAL CLEAN DATASET PREVIEW (FIRST 5 ROWS) ---

,object_id,district,revenue_ci,timeperiod,sum_rain,max_rain,riverlevel_mean,distance_from_river,inundation_pct,sum_population,total_hhd,Crop_Area,road_length,health_centres_count,elevation_mean,slope_mean,Population_affected_Total,affected_pop_ratio
0,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_04,166.249990,0.214262,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
1,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_05,300.919378,0.344883,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
2,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_06,914.725700,1.346394,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
3,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_07,788.617197,0.975052,0.0,1718.766638,0.000000,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0
4,18-300-00101,KOKRAJHAR,Gossaigaon (Pt),2021_08,795.942200,1.308983,0.0,1718.766638,0.005049,327337.78125,62460.0,0.0,197887.351181,49,78.792197,84.47988,0.0,0.0

--- FINAL COLUMN NAMES LIST ---
Column 1: object_id
Column 2: district
Column 3: revenue_ci
Column 4: timeperiod
Column 5: sum_rain
Column 6: max_rain
Column 7: riverlevel_mean
Column 8: distance_from_river
Column 9: inundation_pct
Column 10: sum_population
Column 11: total_hhd
Column 12: Crop_Area
Column 13: road_length
Column 14: health_centres_count
Column 15: elevation_mean
Column 16: slope_mean
Column 17: Population_affected_Total
Column 18: affected_pop_ratio