<a href="https://colab.research.google.com/github/Samriddhi330/Assam-Flood-DSS/blob/main/notebooks/EDA_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assam Flood Impact Prediction — Exploratory Data Analysis

## 1. Data Loading & Initial Inspection

## 2. Data Cleaning & Preparation

## 3. Target Variable Creation

## 4. Impact Distribution

## 5. Temporal Impact Analysis

## 6. Revenue Circle / Spatial Analysis

## 7. Impact Persistence Analysis

## 8. Rainfall and Environmental Analysis

## 9. Feature Availability & Missingness

## 10. Feature Variability / Uniqueness Analysis

## 11. Prediction Problem Formulation

## 12. One-Month-Ahead Prediction Dataset

## 13. Final Prediction Feature Set

## 14. EDA Conclusions

# Assam Flood Impact Prediction — Exploratory Data Analysis

## 1. Environment and Data Loading

In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

project_folder = "/content/drive/MyDrive/Assam_Flood_DSS"

os.makedirs(project_folder, exist_ok=True)

print("Project folder:", project_folder)
print("Folder created/verified successfully!")

Project folder: /content/drive/MyDrive/Assam_Flood_DSS
Folder created/verified successfully!

In [5]:
import os

os.chdir(project_folder)

if not os.path.exists("flood-data-ecosystem-Assam"):
    !git clone https://github.com/CivicDataLab/flood-data-ecosystem-Assam.git
    print("Repository cloned successfully!")
else:
    print("Repository already exists.")

Repository already exists.

In [6]:
import os

dataset_path = os.path.join(
    project_folder,
    "flood-data-ecosystem-Assam",
    "Sources",
    "MASTER_VARIABLES.csv"
)

print("Dataset path:")
print(dataset_path)

if os.path.exists(dataset_path):
    print("\nMASTER_VARIABLES.csv found successfully!")
else:
    print("\nERROR: MASTER_VARIABLES.csv was not found.")

Dataset path:
/content/drive/MyDrive/Assam_Flood_DSS/flood-data-ecosystem-Assam/Sources/MASTER_VARIABLES.csv

MASTER_VARIABLES.csv found successfully!

In [7]:
import os
import pandas as pd

source_folder = "/content/drive/MyDrive/Assam_Flood_DSS/flood-data-ecosystem-Assam"

## 2. Dataset Overview and Structure

In [8]:
df = pd.read_csv(dataset_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 11160
Columns: 85

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11160 entries, 0 to 11159
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   object_id                                     11160 non-null  object
 1   district                                      11160 non-null  object
 2   rc_area                                       11160 non-null  int64
 3   timeperiod                                    11160 non-null  object
 4   total_tender_awarded_value                    11160 non-null  float64
 5   erosion_tenders_awarded_value                 11160 non-null  float64
 6   SOPD_tenders_awarded_value                    11160 non-null  float64
 7   SDRF_sanctions_awarded_value                  11160 non-null  float64
 8   SDRF_tenders_awarded_value                    11160 non-null  float64
 9   RIDF_tenders_awarded_value                    11160 non-null  float64
 10  LTIF_tenders_awarded_value                    11160 non-null  float64
 11  CIDF_tenders_awarded_value                    11160 non-null  float64
 12  Preparedness Measures_tenders_awarded_value   11160 non-null  float64
 13  Immediate Measures_tenders_awarded_value      11160 non-null  float64
 14  Others_tenders_awarded_value                  11160 non-null  float64
 15  Repair and Restoration_tenders_awarded_value  11160 non-null  float64
 16  Total_Animal_Washed_Away                      11160 non-null  float64
 17  Total_Animal_Affected                         11160 non-null  float64
 18  Population_affected_Total                     11160 non-null  float64
 19  Crop_Area                                     11160 non-null  float64
 20  Male_Camp                                     11160 non-null  float64
 21  Female_Camp                                   11160 non-null  float64
 22  Children_Camp                                 11160 non-null  float64
 23  Total_House_Fully_Damaged                     11160 non-null  float64
 24  Human_Live_Lost                               11160 non-null  int64
 25  Human_Live_Lost_Children                      11160 non-null  float64
 26  Human_Live_Lost_Female                        11160 non-null  float64
 27  Human_Live_Lost_Male                          11160 non-null  float64
 28  Embankments affected                          11160 non-null  float64
 29  Roads                                         11160 non-null  float64
 30  Bridge                                        11160 non-null  float64
 31  Embankment breached                           11160 non-null  float64
 32  max_rain                                      11160 non-null  float64
 33  mean_rain                                     11160 non-null  float64
 34  sum_rain                                      11160 non-null  float64
 35  mean_ndvi                                     11160 non-null  float64
 36  mean_ndbi                                     11160 non-null  float64
 37  count                                         11160 non-null  float64
 38  inundation_pct                                11160 non-null  float64
 39  inundation_intensity_mean                     11160 non-null  float64
 40  inundation_intensity_mean_nonzero             11160 non-null  float64
 41  inundation_intensity_sum                      11160 non-null  float64
 42  riverlevel_mean                               11160 non-null  float64
 43  riverlevel_min                                11160 non-null  float64
 44  riverlevel_max                                11160 non-null  float64
 45  total_expenditure_value                       11160 non-null  float64
 46  SDRF_expenditure_value                        11160 non-null  float64
 47  Immediate Measures_expenditure_value          11160 non-null  float64
 48  Others_expenditure_value                      11160 non-null  float64
 49  Repair and Restoration_expenditure_value      11160 non-null  float64
 50  Relief Camps                                  11160 non-null  float64
 51  Relief Centers                                11160 non-null  float64
 52  Relief Inmates                                11160 non-null  float64
 53  Relief_Camp_inmates                           11160 non-null  int64
 54  mean_sex_ratio                                11160 non-null  float64
 55  sum_aged_population                           11160 non-null  float64
 56  sum_young_population                          11160 non-null  float64
 57  sum_population                                11160 non-null  float64
 58  water                                         11160 non-null  float64
 59  trees                                         11160 non-null  float64
 60  flooded_vegetation                            11160 non-null  float64
 61  crops                                         11160 non-null  float64
 62  built_area                                    11160 non-null  float64
 63  bare_ground                                   11160 non-null  float64
 64  clouds                                        11160 non-null  float64
 65  rangeland                                     11160 non-null  float64
 66  schools_count                                 11160 non-null  int64
 67  health_centres_count                          11160 non-null  int64
 68  rail_length                                   11160 non-null  float64
 69  rail_count                                    11160 non-null  float64
 70  road_length                                   11160 non-null  float64
 71  mean_cn                                       11160 non-null  float64
 72  elevation_mean                                11160 non-null  float64
 73  slope_mean                                    11160 non-null  float64
 74  revenue_ci                                    11160 non-null  object
 75  dtname                                        11160 non-null  object
 76  dtcode11                                      11160 non-null  object
 77  net_sown_area_in_hac                          11160 non-null  float64
 78  avg_electricity                               11160 non-null  float64
 79  avg_tele                                      11160 non-null  float64
 80  rc_piped_hhds_pct                             11160 non-null  float64
 81  rc_nosanitation_hhds_pct                      11160 non-null  float64
 82  total_hhd                                     11160 non-null  float64
 83  distance_from_river                           11160 non-null  float64
 84  drainage_density                              11160 non-null  float64
dtypes: float64(74), int64(5), object(6)
memory usage: 7.2+ MB

In [10]:
for i, column in enumerate(df.columns, start=1):
    print(i, ":", column)

1 : object_id
2 : district
3 : rc_area
4 : timeperiod
5 : total_tender_awarded_value
6 : erosion_tenders_awarded_value
7 : SOPD_tenders_awarded_value
8 : SDRF_sanctions_awarded_value
9 : SDRF_tenders_awarded_value
10 : RIDF_tenders_awarded_value
11 : LTIF_tenders_awarded_value
12 : CIDF_tenders_awarded_value
13 : Preparedness Measures_tenders_awarded_value
14 : Immediate Measures_tenders_awarded_value
15 : Others_tenders_awarded_value
16 : Repair and Restoration_tenders_awarded_value
17 : Total_Animal_Washed_Away
18 : Total_Animal_Affected
19 : Population_affected_Total
20 : Crop_Area
21 : Male_Camp
22 : Female_Camp
23 : Children_Camp
24 : Total_House_Fully_Damaged
25 : Human_Live_Lost
26 : Human_Live_Lost_Children
27 : Human_Live_Lost_Female
28 : Human_Live_Lost_Male
29 : Embankments affected
30 : Roads
31 : Bridge
32 : Embankment breached
33 : max_rain
34 : mean_rain
35 : sum_rain
36 : mean_ndvi
37 : mean_ndbi
38 : count
39 : inundation_pct
40 : inundation_intensity_mean
41 : inundation_intensity_mean_nonzero
42 : inundation_intensity_sum
43 : riverlevel_mean
44 : riverlevel_min
45 : riverlevel_max
46 : total_expenditure_value
47 : SDRF_expenditure_value
48 : Immediate Measures_expenditure_value
49 : Others_expenditure_value
50 : Repair and Restoration_expenditure_value
51 : Relief Camps
52 : Relief Centers
53 : Relief Inmates
54 : Relief_Camp_inmates
55 : mean_sex_ratio
56 : sum_aged_population
57 : sum_young_population
58 : sum_population
59 : water
60 : trees
61 : flooded_vegetation
62 : crops
63 : built_area
64 : bare_ground
65 : clouds
66 : rangeland
67 : schools_count
68 : health_centres_count
69 : rail_length
70 : rail_count
71 : road_length
72 : mean_cn
73 : elevation_mean
74 : slope_mean
75 : revenue_ci
76 : dtname
77 : dtcode11
78 : net_sown_area_in_hac
79 : avg_electricity
80 : avg_tele
81 : rc_piped_hhds_pct
82 : rc_nosanitation_hhds_pct
83 : total_hhd
84 : distance_from_river
85 : drainage_density

## 3. Data Quality and Missing Values

In [11]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    by="Missing_Count",
    ascending=False
)

missing

                            Missing_Count  Missing_Percentage
object_id                               0                 0.0
district                                0                 0.0
rc_area                                 0                 0.0
timeperiod                              0                 0.0
total_tender_awarded_value              0                 0.0
...                                   ...                 ...
rc_piped_hhds_pct                       0                 0.0
rc_nosanitation_hhds_pct                0                 0.0
total_hhd                               0                 0.0
distance_from_river                     0                 0.0
drainage_density                        0                 0.0

[85 rows x 2 columns]

In [12]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [13]:
identifier_columns = [
    "object_id",
    "district",
    "revenue_ci",
    "dtname",
    "dtcode11",
    "timeperiod"
]

for column in identifier_columns:
    print(
        column,
        "→",
        df[column].nunique(),
        "unique values"
    )

object_id → 180 unique values
district → 35 unique values
revenue_ci → 159 unique values
dtname → 36 unique values
dtcode11 → 36 unique values
timeperiod → 62 unique values

In [14]:
sorted(df["timeperiod"].unique())

['2021_04',
 '2021_05',
 '2021_06',
 '2021_07',
 '2021_08',
 '2021_09',
 '2021_10',
 '2021_11',
 '2021_12',
 '2022_01',
 '2022_02',
 '2022_03',
 '2022_04',
 '2022_05',
 '2022_06',
 '2022_07',
 '2022_08',
 '2022_09',
 '2022_10',
 '2022_11',
 '2022_12',
 '2023_01',
 '2023_02',
 '2023_03',
 '2023_04',
 '2023_05',
 '2023_06',
 '2023_07',
 '2023_08',
 '2023_09',
 '2023_10',
 '2023_11',
 '2023_12',
 '2024_01',
 '2024_02',
 '2024_03',
 '2024_04',
 '2024_05',
 '2024_06',
 '2024_07',
 '2024_08',
 '2024_09',
 '2024_10',
 '2024_11',
 '2024_12',
 '2025_01',
 '2025_02',
 '2025_03',
 '2025_04',
 '2025_05',
 '2025_06',
 '2025_07',
 '2025_08',
 '2025_09',
 '2025_10',
 '2025_11',
 '2025_12',
 '2026_01',
 '2026_02',
 '2026_03',
 '2026_04',
 '2026_05']

In [15]:
time_counts = df["timeperiod"].value_counts().sort_index()

time_counts

timeperiod
2021_04    180
2021_05    180
2021_06    180
2021_07    180
2021_08    180
          ...
2026_01    180
2026_02    180
2026_03    180
2026_04    180
2026_05    180
Name: count, Length: 62, dtype: int64

In [16]:
id_time_counts = df.groupby("object_id")["timeperiod"].nunique()

print("Number of spatial units:", id_time_counts.size)
print("Minimum months per spatial unit:", id_time_counts.min())
print("Maximum months per spatial unit:", id_time_counts.max())

Number of spatial units: 180
Minimum months per spatial unit: 62
Maximum months per spatial unit: 62

In [17]:
object_revenue = df.groupby("object_id")["revenue_ci"].nunique()

print("Minimum revenue circles per object_id:", object_revenue.min())
print("Maximum revenue circles per object_id:", object_revenue.max())

Minimum revenue circles per object_id: 1
Maximum revenue circles per object_id: 1

In [18]:
revenue_object = df.groupby("revenue_ci")["object_id"].nunique()

print("Minimum object_ids per revenue_ci:", revenue_object.min())
print("Maximum object_ids per revenue_ci:", revenue_object.max())

Minimum object_ids per revenue_ci: 1
Maximum object_ids per revenue_ci: 4

In [19]:
duplicate_columns = df.columns[df.columns.duplicated()]

print("Number of duplicate column names:", len(duplicate_columns))

if len(duplicate_columns) > 0:
    print("\nDuplicate column names:")
    print(duplicate_columns.tolist())
else:
    print("No duplicate column names found.")

Number of duplicate column names: 0
No duplicate column names found.

In [20]:
unique_counts = df.nunique()

constant_columns = unique_counts[unique_counts == 1]

print("Number of constant columns:", len(constant_columns))

if len(constant_columns) > 0:
    print("\nConstant columns:")
    print(constant_columns)
else:
    print("No constant columns found.")

Number of constant columns: 1

Constant columns:
LTIF_tenders_awarded_value    1
dtype: int64

In [21]:
unique_counts = df.nunique().sort_values()

unique_counts.head(15)

LTIF_tenders_awarded_value                   1
avg_tele                                     2
CIDF_tenders_awarded_value                   3
Human_Live_Lost_Female                       4
Human_Live_Lost_Children                     6
Human_Live_Lost_Male                         7
Others_expenditure_value                    11
Human_Live_Lost                             11
clouds                                      11
Repair and Restoration_expenditure_value    11
Embankment breached                         13
Bridge                                      13
Embankments affected                        15
rail_count                                  31
district                                    35
dtype: int64

In [22]:
low_cardinality_columns = unique_counts[unique_counts <= 3].index

for column in low_cardinality_columns:
    print(f"\n{column}")
    print(df[column].unique())

LTIF_tenders_awarded_value
[0.]

avg_tele
[2. 3.]

CIDF_tenders_awarded_value
[      0.   5558319.75 9043914.  ]

In [23]:
numeric_columns = df.select_dtypes(include=np.number).columns

negative_counts = (df[numeric_columns] < 0).sum()

negative_counts = negative_counts[negative_counts > 0]

print("Columns containing negative values:", len(negative_counts))

if len(negative_counts) > 0:
    print("\nNegative-value counts:")
    print(negative_counts)
else:
    print("No negative values found in numerical columns.")

Columns containing negative values: 2

Negative-value counts:
mean_ndvi      12
mean_ndbi    9967
dtype: int64

In [24]:
for column in ["mean_ndvi", "mean_ndbi"]:
    print(f"\n{column}")
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())
    print("Mean:", df[column].mean())

mean_ndvi
Minimum: -0.0987346131922835
Maximum: 0.8879881434970431
Mean: 0.4723490328759357

mean_ndbi
Minimum: -0.5797126706966684
Maximum: 0.1285071439587342
Mean: -0.12328013696670813

In [25]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
rc_area,11160.0,4.361667e+02,4.515593e+02,2.000000,177.750000,323.500000,516.250000,3.303000e+03
total_tender_awarded_value,11160.0,2.083011e+06,2.126145e+07,0.000000,0.000000,0.000000,0.000000,9.153370e+08
erosion_tenders_awarded_value,11160.0,5.907171e+05,1.271151e+07,0.000000,0.000000,0.000000,0.000000,9.153370e+08
SOPD_tenders_awarded_value,11160.0,4.719034e+05,7.630328e+06,0.000000,0.000000,0.000000,0.000000,4.436202e+08
SDRF_sanctions_awarded_value,11160.0,1.202300e+06,1.294120e+07,0.000000,0.000000,0.000000,0.000000,3.868200e+08
...,...,...,...,...,...,...,...,...
rc_piped_hhds_pct,11160.0,4.624789e+00,4.667592e+00,0.000000,1.138141,3.169582,6.553539,2.253725e+01
rc_nosanitation_hhds_pct,11160.0,1.757118e+01,9.667217e+00,0.163423,10.445022,16.350903,21.998785,6.938776e+01
total_hhd,11160.0,4.384660e+04,3.472433e+04,0.000000,21471.000000,38531.000000,56887.500000,2.577250e+05
distance_from_river,11160.0,3.314734e+03,3.021348e+03,379.126625,1328.473449,2327.260688,4050.430116,1.889500e+04
drainage_density,11160.0,5.819389e-04,9.373343e-05,0.000247,0.000535,0.000602,0.000652,7.300000e-04

In [26]:
numeric_columns = df.select_dtypes(include=np.number).columns

infinite_counts = np.isinf(df[numeric_columns]).sum()

infinite_counts = infinite_counts[infinite_counts > 0]

print("Columns containing infinite values:", len(infinite_counts))

if len(infinite_counts) > 0:
    print("\nInfinite-value counts:")
    print(infinite_counts)
else:
    print("No infinite values found.")

Columns containing infinite values: 0
No infinite values found.

In [27]:
object_columns = df.select_dtypes(include="object").columns

for column in object_columns:
    blank_count = df[column].astype(str).str.strip().eq("").sum()
    print(f"{column}: {blank_count} blank values")

object_id: 0 blank values
district: 0 blank values
timeperiod: 0 blank values
revenue_ci: 0 blank values
dtname: 0 blank values
dtcode11: 0 blank values

In [28]:
for column in object_columns:
    original = df[column].astype(str)
    cleaned = original.str.strip()

    differences = (original != cleaned).sum()

    print(f"{column}: {differences} values with extra whitespace")

object_id: 0 values with extra whitespace
district: 0 values with extra whitespace
timeperiod: 0 values with extra whitespace
revenue_ci: 0 values with extra whitespace
dtname: 0 values with extra whitespace
dtcode11: 0 values with extra whitespace

In [29]:
object_district = df.groupby("object_id")["district"].nunique()

print("Minimum districts per object_id:", object_district.min())
print("Maximum districts per object_id:", object_district.max())

Minimum districts per object_id: 1
Maximum districts per object_id: 1

In [30]:
object_dtname = df.groupby("object_id")["dtname"].nunique()

print("Minimum dtname values per object_id:", object_dtname.min())
print("Maximum dtname values per object_id:", object_dtname.max())

Minimum dtname values per object_id: 1
Maximum dtname values per object_id: 1

In [31]:
object_dtcode = df.groupby("object_id")["dtcode11"].nunique()

print("Minimum dtcode11 values per object_id:", object_dtcode.min())
print("Maximum dtcode11 values per object_id:", object_dtcode.max())

Minimum dtcode11 values per object_id: 1
Maximum dtcode11 values per object_id: 1

In [32]:
dtcode_dtname = df.groupby("dtcode11")["dtname"].nunique()

print("Minimum dtname values per dtcode11:", dtcode_dtname.min())
print("Maximum dtname values per dtcode11:", dtcode_dtname.max())

Minimum dtname values per dtcode11: 1
Maximum dtname values per dtcode11: 1

In [33]:
variable_info = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": df.nunique().values,
    "Missing_Values": df.isnull().sum().values
})

variable_info

                        Column Data_Type  Unique_Values  Missing_Values
0                    object_id    object            180               0
1                     district    object             35               0
2                      rc_area     int64            169               0
3                   timeperiod    object             62               0
4   total_tender_awarded_value   float64            379               0
..                         ...       ...            ...             ...
80           rc_piped_hhds_pct   float64            171               0
81    rc_nosanitation_hhds_pct   float64            179               0
82                   total_hhd   float64            177               0
83         distance_from_river   float64            180               0
84            drainage_density   float64            143               0

[85 rows x 4 columns]

In [34]:
id_columns = [
    "object_id",
    "district",
    "revenue_ci",
    "dtname",
    "dtcode11"
]

time_column = "timeperiod"

print("Spatial identifier columns:")
for column in id_columns:
    print("-", column)

print("\nTime column:")
print("-", time_column)

Spatial identifier columns:
- object_id
- district
- revenue_ci
- dtname
- dtcode11

Time column:
- timeperiod

In [35]:
identifier_columns = id_columns + [time_column]

feature_candidates = [
    column for column in df.columns
    if column not in identifier_columns
]

print("Number of feature candidates:", len(feature_candidates))

print("\nFeature candidates:")
for i, column in enumerate(feature_candidates, start=1):
    print(i, ":", column)

Number of feature candidates: 79

Feature candidates:
1 : rc_area
2 : total_tender_awarded_value
3 : erosion_tenders_awarded_value
4 : SOPD_tenders_awarded_value
5 : SDRF_sanctions_awarded_value
6 : SDRF_tenders_awarded_value
7 : RIDF_tenders_awarded_value
8 : LTIF_tenders_awarded_value
9 : CIDF_tenders_awarded_value
10 : Preparedness Measures_tenders_awarded_value
11 : Immediate Measures_tenders_awarded_value
12 : Others_tenders_awarded_value
13 : Repair and Restoration_tenders_awarded_value
14 : Total_Animal_Washed_Away
15 : Total_Animal_Affected
16 : Population_affected_Total
17 : Crop_Area
18 : Male_Camp
19 : Female_Camp
20 : Children_Camp
21 : Total_House_Fully_Damaged
22 : Human_Live_Lost
23 : Human_Live_Lost_Children
24 : Human_Live_Lost_Female
25 : Human_Live_Lost_Male
26 : Embankments affected
27 : Roads
28 : Bridge
29 : Embankment breached
30 : max_rain
31 : mean_rain
32 : sum_rain
33 : mean_ndvi
34 : mean_ndbi
35 : count
36 : inundation_pct
37 : inundation_intensity_mean
38 : inundation_intensity_mean_nonzero
39 : inundation_intensity_sum
40 : riverlevel_mean
41 : riverlevel_min
42 : riverlevel_max
43 : total_expenditure_value
44 : SDRF_expenditure_value
45 : Immediate Measures_expenditure_value
46 : Others_expenditure_value
47 : Repair and Restoration_expenditure_value
48 : Relief Camps
49 : Relief Centers
50 : Relief Inmates
51 : Relief_Camp_inmates
52 : mean_sex_ratio
53 : sum_aged_population
54 : sum_young_population
55 : sum_population
56 : water
57 : trees
58 : flooded_vegetation
59 : crops
60 : built_area
61 : bare_ground
62 : clouds
63 : rangeland
64 : schools_count
65 : health_centres_count
66 : rail_length
67 : rail_count
68 : road_length
69 : mean_cn
70 : elevation_mean
71 : slope_mean
72 : net_sown_area_in_hac
73 : avg_electricity
74 : avg_tele
75 : rc_piped_hhds_pct
76 : rc_nosanitation_hhds_pct
77 : total_hhd
78 : distance_from_river
79 : drainage_density

## 4. Feature Classification & Variable Understanding

In [36]:
environmental_variables = [
    "max_rain",
    "mean_rain",
    "sum_rain",
    "mean_ndvi",
    "mean_ndbi",
    "inundation_pct",
    "inundation_intensity_mean",
    "inundation_intensity_mean_nonzero",
    "inundation_intensity_sum",
    "riverlevel_mean",
    "riverlevel_min",
    "riverlevel_max",
    "water",
    "trees",
    "flooded_vegetation",
    "crops",
    "built_area",
    "bare_ground",
    "clouds",
    "rangeland",
    "mean_cn",
    "elevation_mean",
    "slope_mean",
    "distance_from_river",
    "drainage_density"
]

exposure_vulnerability_variables = [
    "rc_area",
    "mean_sex_ratio",
    "sum_aged_population",
    "sum_young_population",
    "sum_population",
    "schools_count",
    "health_centres_count",
    "rail_length",
    "rail_count",
    "road_length",
    "net_sown_area_in_hac",
    "avg_electricity",
    "avg_tele",
    "rc_piped_hhds_pct",
    "rc_nosanitation_hhds_pct",
    "total_hhd"
]

flood_impact_variables = [
    "Total_Animal_Washed_Away",
    "Total_Animal_Affected",
    "Population_affected_Total",
    "Crop_Area",
    "Male_Camp",
    "Female_Camp",
    "Children_Camp",
    "Total_House_Fully_Damaged",
    "Human_Live_Lost",
    "Human_Live_Lost_Children",
    "Human_Live_Lost_Female",
    "Human_Live_Lost_Male",
    "Embankments affected",
    "Roads",
    "Bridge",
    "Embankment breached"
]

response_variables = [
    "total_tender_awarded_value",
    "erosion_tenders_awarded_value",
    "SOPD_tenders_awarded_value",
    "SDRF_sanctions_awarded_value",
    "SDRF_tenders_awarded_value",
    "RIDF_tenders_awarded_value",
    "LTIF_tenders_awarded_value",
    "CIDF_tenders_awarded_value",
    "Preparedness Measures_tenders_awarded_value",
    "Immediate Measures_tenders_awarded_value",
    "Others_tenders_awarded_value",
    "Repair and Restoration_tenders_awarded_value",
    "total_expenditure_value",
    "SDRF_expenditure_value",
    "Immediate Measures_expenditure_value",
    "Others_expenditure_value",
    "Repair and Restoration_expenditure_value",
    "Relief Camps",
    "Relief Centers",
    "Relief Inmates",
    "Relief_Camp_inmates"
]

print("Environmental variables:", len(environmental_variables))
print("Exposure/vulnerability variables:", len(exposure_vulnerability_variables))
print("Flood-impact variables:", len(flood_impact_variables))
print("Response variables:", len(response_variables))

total_classified = (
    len(environmental_variables)
    + len(exposure_vulnerability_variables)
    + len(flood_impact_variables)
    + len(response_variables)
)

print("\nTotal classified variables:", total_classified)
print("Total candidate variables:", len(feature_candidates))

Environmental variables: 25
Exposure/vulnerability variables: 16
Flood-impact variables: 16
Response variables: 21

Total classified variables: 78
Total candidate variables: 79

In [37]:
print("count variable:")
print("Data type:", df["count"].dtype)
print("Unique values:", df["count"].nunique())
print("Minimum:", df["count"].min())
print("Maximum:", df["count"].max())
print("Mean:", df["count"].mean())
print("Median:", df["count"].median())

count variable:
Data type: float64
Unique values: 1438
Minimum: 0.0
Maximum: 59204.0
Mean: 2534.234318996416
Median: 0.0

## 5. Target Variable Investigation

In [38]:
# Inspect the two variables that may be used to construct the target

print("Population_affected_Total")
print(df["Population_affected_Total"].describe())
print("\nMissing values:", df["Population_affected_Total"].isna().sum())

print("\n" + "="*60)

print("sum_population")
print(df["sum_population"].describe())
print("\nMissing values:", df["sum_population"].isna().sum())

Population_affected_Total
count     11160.000000
mean       1765.417025
std       17140.632595
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      725306.000000
Name: Population_affected_Total, dtype: float64

Missing values: 0

============================================================
sum_population
count     11160.000000
mean     200416.285275
std      136671.304638
min         147.727197
25%      106905.579687
50%      174818.996875
75%      270639.153125
max      771952.975000
Name: sum_population, dtype: float64

Missing values: 0

In [39]:
# Temporarily calculate the proposed affected population ratio
affected_ratio = (
    df["Population_affected_Total"] / df["sum_population"]
)

print("Number of observations:", len(affected_ratio))

print("\nNon-zero affected population:")
print((df["Population_affected_Total"] > 0).sum())

print("\nZero affected population:")
print((df["Population_affected_Total"] == 0).sum())

print("\nProposed ratio statistics:")
print(affected_ratio.describe())

print("\nRatios greater than 1:")
print((affected_ratio > 1).sum())

print("\nMaximum ratio:")
print(affected_ratio.max())

Number of observations: 11160

Non-zero affected population:
877

Zero affected population:
10283

Proposed ratio statistics:
count    11160.000000
mean         0.008417
std          0.094955
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          7.534265
dtype: float64

Ratios greater than 1:
10

Maximum ratio:
7.534265264420457

In [40]:
# Find observations where affected population exceeds total population

invalid_ratio = df[
    df["Population_affected_Total"] > df["sum_population"]
].copy()

print("Number of observations with ratio > 1:", len(invalid_ratio))

print("\nRelevant columns:")
print(
    invalid_ratio[
        [
            "object_id",
            "district",
            "revenue_ci",
            "dtname",
            "dtcode11",
            "timeperiod",
            "Population_affected_Total",
            "sum_population"
        ]
    ].to_string(index=False)
)

Number of observations with ratio > 1: 10

Relevant columns:
   object_id   district    revenue_ci     dtname dtcode11 timeperiod  Population_affected_Total  sum_population
18-301-00114     DHUBRI   Chapar (Pt)     DHUBRI   18-301    2024_07                   126235.0    69862.817187
18-303-00121    BARPETA       Baghbor    BARPETA   18-303    2022_06                   370497.0   332325.637500
18-303-00123    BARPETA    Sarthebari    BARPETA   18-303    2022_06                   250640.0   223127.412500
18-318-00194 HAILAKANDI       Algapur HAILAKANDI   18-318    2022_07                   190660.0   124099.114062
18-321-00211     KAMRUP          Hajo     KAMRUP   18-321    2022_06                   554659.0    73618.193750
18-323-00224    NALBARI     Barkhetri    NALBARI   18-323    2022_06                   269330.0   250136.059375
18-325-00239    DARRANG      Sipajhar    DARRANG   18-325    2022_06                   154678.0   145347.975000
18-799-00124     BAJALI   Bajali (Pt)     BAJALI   18-799    2022_06                   161000.0   122928.981250
18-799-00124     BAJALI   Bajali (Pt)     BAJALI   18-799    2023_06                   195000.0   124143.784375
18-799-00265     BAJALI Sarupeta (Pt)     BAJALI   18-799    2022_06                   195000.0   171725.087500

In [41]:
# Check how much each population variable changes within the same spatial unit

population_variation = df.groupby("object_id").agg(
    population_min=("sum_population", "min"),
    population_max=("sum_population", "max"),
    population_unique=("sum_population", "nunique"),
    affected_nonzero_months=(
        "Population_affected_Total",
        lambda x: (x > 0).sum()
    ),
    affected_max=("Population_affected_Total", "max")
)

print(population_variation.describe())

print("\nNumber of spatial units where sum_population never changes:")
print(
    (population_variation["population_unique"] == 1).sum(),
    "out of",
    len(population_variation)
)

print("\nNumber of spatial units where sum_population changes:")
print(
    (population_variation["population_unique"] > 1).sum(),
    "out of",
    len(population_variation)
)

       population_min  population_max  population_unique  \
count      180.000000      180.000000              180.0
mean    196104.167526   205299.161858                6.0
std     133734.040979   140757.236747                0.0
min        147.727197      163.371484                6.0
25%     105099.197461   110433.926172                6.0
50%     171775.714844   179535.410156                6.0
75%     266202.475391   275595.640625                6.0
max     737687.131250   771952.975000                6.0

       affected_nonzero_months   affected_max
count               180.000000     180.000000
mean                  4.872222   50650.088889
std                   4.458412   93359.569071
min                   0.000000       0.000000
25%                   0.000000       0.000000
50%                   4.000000   12631.000000
75%                   7.000000   58508.750000
max                  23.000000  725306.000000

Number of spatial units where sum_population never changes:
0 out of 180

Number of spatial units where sum_population changes:
180 out of 180

In [42]:
# Examine how sum_population changes over time

population_periods = (
    df.groupby("timeperiod")["sum_population"]
      .agg(["min", "max", "mean", "nunique"])
      .reset_index()
)

print(population_periods.to_string(index=False))

timeperiod        min          max          mean  nunique
   2021_04 147.727197 737687.13125 196278.283737      180
   2021_05 147.727197 737687.13125 196278.283737      180
   2021_06 147.727197 737687.13125 196278.283737      180
   2021_07 147.727197 737687.13125 196278.283737      180
   2021_08 147.727197 737687.13125 196278.283737      180
   2021_09 147.727197 737687.13125 196278.283737      180
   2021_10 147.727197 737687.13125 196278.283737      180
   2021_11 147.727197 737687.13125 196278.283737      180
   2021_12 147.727197 737687.13125 196278.283737      180
   2022_01 150.856055 744540.30000 198047.636119      180
   2022_02 150.856055 744540.30000 198047.636119      180
   2022_03 150.856055 744540.30000 198047.636119      180
   2022_04 150.856055 744540.30000 198047.636119      180
   2022_05 150.856055 744540.30000 198047.636119      180
   2022_06 150.856055 744540.30000 198047.636119      180
   2022_07 150.856055 744540.30000 198047.636119      180
   2022_08 150.856055 744540.30000 198047.636119      180
   2022_09 150.856055 744540.30000 198047.636119      180
   2022_10 150.856055 744540.30000 198047.636119      180
   2022_11 150.856055 744540.30000 198047.636119      180
   2022_12 150.856055 744540.30000 198047.636119      180
   2023_01 153.984912 751393.46875 199816.988501      180
   2023_02 153.984912 751393.46875 199816.988501      180
   2023_03 153.984912 751393.46875 199816.988501      180
   2023_04 153.984912 751393.46875 199816.988501      180
   2023_05 153.984912 751393.46875 199816.988501      180
   2023_06 153.984912 751393.46875 199816.988501      180
   2023_07 153.984912 751393.46875 199816.988501      180
   2023_08 153.984912 751393.46875 199816.988501      180
   2023_09 153.984912 751393.46875 199816.988501      180
   2023_10 153.984912 751393.46875 199816.988501      180
   2023_11 153.984912 751393.46875 199816.988501      180
   2023_12 153.984912 751393.46875 199816.988501      180
   2024_01 157.113770 758246.63750 201586.340883      180
   2024_02 157.113770 758246.63750 201586.340883      180
   2024_03 157.113770 758246.63750 201586.340883      180
   2024_04 157.113770 758246.63750 201586.340883      180
   2024_05 157.113770 758246.63750 201586.340883      180
   2024_06 157.113770 758246.63750 201586.340883      180
   2024_07 157.113770 758246.63750 201586.340883      180
   2024_08 157.113770 758246.63750 201586.340883      180
   2024_09 157.113770 758246.63750 201586.340883      180
   2024_10 157.113770 758246.63750 201586.340883      180
   2024_11 157.113770 758246.63750 201586.340883      180
   2024_12 157.113770 758246.63750 201586.340883      180
   2025_01 160.242627 765099.80625 203355.693265      180
   2025_02 160.242627 765099.80625 203355.693265      180
   2025_03 160.242627 765099.80625 203355.693265      180
   2025_04 160.242627 765099.80625 203355.693265      180
   2025_05 160.242627 765099.80625 203355.693265      180
   2025_06 160.242627 765099.80625 203355.693265      180
   2025_07 160.242627 765099.80625 203355.693265      180
   2025_08 160.242627 765099.80625 203355.693265      180
   2025_09 160.242627 765099.80625 203355.693265      180
   2025_10 160.242627 765099.80625 203355.693265      180
   2025_11 160.242627 765099.80625 203355.693265      180
   2025_12 160.242627 765099.80625 203355.693265      180
   2026_01 163.371484 771952.97500 205125.045647      180
   2026_02 163.371484 771952.97500 205125.045647      180
   2026_03 163.371484 771952.97500 205125.045647      180
   2026_04 163.371484 771952.97500 205125.045647      180
   2026_05 163.371484 771952.97500 205125.045647      180

In [43]:

# Compare affected population with the annual population estimate

print("Affected population / population ratio by year:\n")

# Create the ratio if it does not already exist
if "affected_to_population" not in df.columns:
    df["affected_to_population"] = (
        df["Population_affected_Total"] /
        df["sum_population"].replace(0, np.nan)
    )

year_ratio = (
    df.groupby(df["timeperiod"].astype(str).str[:4])["affected_to_population"]
      .agg([
          ("mean", "mean"),
          ("median", "median"),
          ("max", "max"),
          ("nonzero", lambda x: (x > 0).sum()),
          ("above_1", lambda x: (x > 1).sum())
      ])
)

print(year_ratio)

Affected population / population ratio by year:

                mean  median       max  nonzero  above_1
timeperiod
2021        0.004660     0.0  0.486857      109        0
2022        0.024367     0.0  7.534265      264        8
2023        0.005130     0.0  1.570759      174        1
2024        0.008486     0.0  1.806898      192        1
2025        0.002005     0.0  0.743121      134        0
2026        0.000017     0.0  0.007999        4        0

In [44]:
# Load the master variable dictionary

master_variables_path = os.path.join(
    source_folder,
    "Sources",
    "MASTER_VARIABLES.csv"
)

master_vars = pd.read_csv(master_variables_path)

print("Shape:", master_vars.shape)
print("\nColumns:")
print(master_vars.columns.tolist())

print("\nRows containing our variables:")
print(
    master_vars[
        master_vars.astype(str)
        .apply(
            lambda row: row.str.contains(
                "Population_affected_Total|sum_population",
                case=False,
                na=False
            ).any(),
            axis=1
        )
    ].to_string(index=False)
)

Shape: (11160, 85)

Columns:
['object_id', 'district', 'rc_area', 'timeperiod', 'total_tender_awarded_value', 'erosion_tenders_awarded_value', 'SOPD_tenders_awarded_value', 'SDRF_sanctions_awarded_value', 'SDRF_tenders_awarded_value', 'RIDF_tenders_awarded_value', 'LTIF_tenders_awarded_value', 'CIDF_tenders_awarded_value', 'Preparedness Measures_tenders_awarded_value', 'Immediate Measures_tenders_awarded_value', 'Others_tenders_awarded_value', 'Repair and Restoration_tenders_awarded_value', 'Total_Animal_Washed_Away', 'Total_Animal_Affected', 'Population_affected_Total', 'Crop_Area', 'Male_Camp', 'Female_Camp', 'Children_Camp', 'Total_House_Fully_Damaged', 'Human_Live_Lost', 'Human_Live_Lost_Children', 'Human_Live_Lost_Female', 'Human_Live_Lost_Male', 'Embankments affected', 'Roads', 'Bridge', 'Embankment breached', 'max_rain', 'mean_rain', 'sum_rain', 'mean_ndvi', 'mean_ndbi', 'count', 'inundation_pct', 'inundation_intensity_mean', 'inundation_intensity_mean_nonzero', 'inundation_intensity_sum', 'riverlevel_mean', 'riverlevel_min', 'riverlevel_max', 'total_expenditure_value', 'SDRF_expenditure_value', 'Immediate Measures_expenditure_value', 'Others_expenditure_value', 'Repair and Restoration_expenditure_value', 'Relief Camps', 'Relief Centers', 'Relief Inmates', 'Relief_Camp_inmates', 'mean_sex_ratio', 'sum_aged_population', 'sum_young_population', 'sum_population', 'water', 'trees', 'flooded_vegetation', 'crops', 'built_area', 'bare_ground', 'clouds', 'rangeland', 'schools_count', 'health_centres_count', 'rail_length', 'rail_count', 'road_length', 'mean_cn', 'elevation_mean', 'slope_mean', 'revenue_ci', 'dtname', 'dtcode11', 'net_sown_area_in_hac', 'avg_electricity', 'avg_tele', 'rc_piped_hhds_pct', 'rc_nosanitation_hhds_pct', 'total_hhd', 'distance_from_river', 'drainage_density']

Rows containing our variables:
Empty DataFrame
Columns: [object_id, district, rc_area, timeperiod, total_tender_awarded_value, erosion_tenders_awarded_value, SOPD_tenders_awarded_value, SDRF_sanctions_awarded_value, SDRF_tenders_awarded_value, RIDF_tenders_awarded_value, LTIF_tenders_awarded_value, CIDF_tenders_awarded_value, Preparedness Measures_tenders_awarded_value, Immediate Measures_tenders_awarded_value, Others_tenders_awarded_value, Repair and Restoration_tenders_awarded_value, Total_Animal_Washed_Away, Total_Animal_Affected, Population_affected_Total, Crop_Area, Male_Camp, Female_Camp, Children_Camp, Total_House_Fully_Damaged, Human_Live_Lost, Human_Live_Lost_Children, Human_Live_Lost_Female, Human_Live_Lost_Male, Embankments affected, Roads, Bridge, Embankment breached, max_rain, mean_rain, sum_rain, mean_ndvi, mean_ndbi, count, inundation_pct, inundation_intensity_mean, inundation_intensity_mean_nonzero, inundation_intensity_sum, riverlevel_mean, riverlevel_min, riverlevel_max, total_expenditure_value, SDRF_expenditure_value, Immediate Measures_expenditure_value, Others_expenditure_value, Repair and Restoration_expenditure_value, Relief Camps, Relief Centers, Relief Inmates, Relief_Camp_inmates, mean_sex_ratio, sum_aged_population, sum_young_population, sum_population, water, trees, flooded_vegetation, crops, built_area, bare_ground, clouds, rangeland, schools_count, health_centres_count, rail_length, rail_count, road_length, mean_cn, elevation_mean, slope_mean, revenue_ci, dtname, dtcode11, net_sown_area_in_hac, avg_electricity, avg_tele, rc_piped_hhds_pct, rc_nosanitation_hhds_pct, total_hhd, distance_from_river, drainage_density]
Index: []

In [45]:
import json

rdls_path = os.path.join(
    source_folder,
    "Sources",
    "DRIMS",
    "metadata",
    "rdls.json"
)

with open(rdls_path, "r", errors="ignore") as f:
    rdls = json.load(f)

print(type(rdls))

# Search recursively for our variables
def find_variable(obj, target_names, path="root"):
    if isinstance(obj, dict):
        for key, value in obj.items():
            current_path = f"{path}.{key}"

            if str(key).lower() in [x.lower() for x in target_names]:
                print("\nFOUND KEY:", current_path)
                print(value)

            find_variable(value, target_names, current_path)

    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            find_variable(item, target_names, f"{path}[{i}]")

find_variable(
    rdls,
    ["Population_affected_Total", "sum_population"]
)

<class 'dict'>

In [46]:
# Search the complete metadata text for our variables

rdls_text = json.dumps(rdls, indent=2)

for term in ["Population_affected_Total", "sum_population"]:
    print("\n" + "="*70)
    print("SEARCHING FOR:", term)

    positions = []
    start = 0

    while True:
        pos = rdls_text.lower().find(term.lower(), start)

        if pos == -1:
            break

        positions.append(pos)
        start = pos + len(term)

    print("Occurrences found:", len(positions))

    # Print context around each occurrence
    for pos in positions[:10]:
        print("\n--- Context ---")
        print(rdls_text[max(0, pos-500):pos+1000])

======================================================================
SEARCHING FOR: Population_affected_Total
Occurrences found: 2

--- Context ---
al_House_Fully_Damaged, Total_House_Partially_Damaged per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Total_House_Fully_Damaged.csv"
    },
    {
      "id": "drims-population-affected-master-csv",
      "title": "Harmonized population affected variable (master)",
      "description": "Harmonized monthly Population_affected_Total per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Population_affected_Total.csv"
    },
    {
      "id": "drims-crop-area-master-csv",
      "title": "Harmonized crop area affected variable (master)",
      "description": "Harmonized monthly Crop_Area per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Crop_Area.csv"
    },
    {
      "id": "drims-infrastructure-damage-master-csv",
      "title": "Harmonized infrastructure damage variables (master)",
      "description": "Harmonized monthly Embankments affected, Embankment breached, Bridge, and roads-damaged counts per Revenue Circle

--- Context ---
m-Assam/main/Sources/master/Total_House_Fully_Damaged.csv"
    },
    {
      "id": "drims-population-affected-master-csv",
      "title": "Harmonized population affected variable (master)",
      "description": "Harmonized monthly Population_affected_Total per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Population_affected_Total.csv"
    },
    {
      "id": "drims-crop-area-master-csv",
      "title": "Harmonized crop area affected variable (master)",
      "description": "Harmonized monthly Crop_Area per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Crop_Area.csv"
    },
    {
      "id": "drims-infrastructure-damage-master-csv",
      "title": "Harmonized infrastructure damage variables (master)",
      "description": "Harmonized monthly Embankments affected, Embankment breached, Bridge, and roads-damaged counts per Revenue Circle (object_id).",
      "format": "csv",
      "media_type": "text/csv",
      "temporal_resolution": "P1M",
      "download_url": "https://raw.githubusercontent.com/CivicDataLab/flood-data-ecosystem-Assam/main/Sources/master/Embankments%20affected.csv"
    }
  ]
}

======================================================================
SEARCHING FOR: sum_population
Occurrences found: 0

In [47]:
# Find where sum_population appears in our notebook environment

print("Searching for sum_population in the current notebook variables/code...\n")

# Check whether it exists as a dataframe column
print("Exists in df:", "sum_population" in df.columns)

# Show the column's values for a few observations
print("\nSample values:")
print(df[["object_id", "district", "timeperiod", "sum_population"]].head(15))

Searching for sum_population in the current notebook variables/code...

Exists in df: True

Sample values:
       object_id   district timeperiod  sum_population
0   18-300-00101  KOKRAJHAR    2021_04    327337.78125
1   18-300-00101  KOKRAJHAR    2021_05    327337.78125
2   18-300-00101  KOKRAJHAR    2021_06    327337.78125
3   18-300-00101  KOKRAJHAR    2021_07    327337.78125
4   18-300-00101  KOKRAJHAR    2021_08    327337.78125
5   18-300-00101  KOKRAJHAR    2021_09    327337.78125
6   18-300-00101  KOKRAJHAR    2021_10    327337.78125
7   18-300-00101  KOKRAJHAR    2021_11    327337.78125
8   18-300-00101  KOKRAJHAR    2021_12    327337.78125
9   18-300-00101  KOKRAJHAR    2022_01    326890.05000
10  18-300-00101  KOKRAJHAR    2022_02    326890.05000
11  18-300-00101  KOKRAJHAR    2022_03    326890.05000
12  18-300-00101  KOKRAJHAR    2022_04    326890.05000
13  18-300-00101  KOKRAJHAR    2022_05    326890.05000
14  18-300-00101  KOKRAJHAR    2022_06    326890.05000

In [48]:
# Search the current notebook's input history for where df was created

for i, code in enumerate(In):
    if "df =" in code or "read_csv" in code or "read_excel" in code:
        print(f"\n--- Cell {i} ---")
        print(code)

--- Cell 8 ---
df = pd.read_csv(dataset_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

--- Cell 44 ---
# Load the master variable dictionary

master_variables_path = os.path.join(
    source_folder,
    "Sources",
    "MASTER_VARIABLES.csv"
)

master_vars = pd.read_csv(master_variables_path)

print("Shape:", master_vars.shape)
print("\nColumns:")
print(master_vars.columns.tolist())

print("\nRows containing our variables:")
print(
    master_vars[
        master_vars.astype(str)
        .apply(
            lambda row: row.str.contains(
                "Population_affected_Total|sum_population",
                case=False,
                na=False
            ).any(),
            axis=1
        )
    ].to_string(index=False)
)

--- Cell 48 ---
# Search the current notebook's input history for where df was created

for i, code in enumerate(In):
    if "df =" in code or "read_csv" in code or "read_excel" in code:
        print(f"\n--- Cell {i} ---")
        print(code)

In [49]:
import json

transformer_path = os.path.join(
    source_folder,
    "Sources",
    "ANTYODAYA",
    "scripts",
    "Transformer.ipynb"
)

with open(transformer_path, "r", encoding="utf-8") as f:
    transformer = json.load(f)

print("Cells containing 'sum_population':\n")

for i, cell in enumerate(transformer["cells"]):

    source = "".join(cell.get("source", []))

    if "sum_population" in source.lower():

        print("=" * 80)
        print("CELL:", i)
        print("TYPE:", cell["cell_type"])
        print("=" * 80)
        print(source)
        print()

Cells containing 'sum_population':

================================================================================
CELL: 21
TYPE: code
================================================================================
# TOTAL POPULATION IN EACH URBAN AREA
import rasterio
import rasterstats

worldpop_raster = rasterio.open('/home/krishna/IDS-DRR-Data-Pipeline/Sources/WORLDPOP/data/population_counts/assam_ppp_2020_UNadj.tif')
worldpop_raster_array = worldpop_raster.read(1)

sum_dicts = rasterstats.zonal_stats(assam_urban_shapes.to_crs(worldpop_raster.crs),
                                     worldpop_raster_array,
                                     affine= worldpop_raster.transform,
                                     stats= ['sum'],
                                     nodata=worldpop_raster.nodata,
                                     geojson_out = True)

dfs = []
for rc in sum_dicts:
    dfs.append(pd.DataFrame([rc['properties']]))

pop_zonal_stats_df = pd.concat(dfs).reset_index(drop=True)
pop_zonal_stats_df = pop_zonal_stats_df.rename(columns={'sum':'sum_population'})

================================================================================
CELL: 22
TYPE: code
================================================================================
# Divide population by 4.3 for households
pop_zonal_stats_df['urban_hhd'] = pop_zonal_stats_df['sum_population']/4.3

In [50]:
# Find cells that use pop_zonal_stats_df in the ANTYODAYA Transformer

for i, cell in enumerate(transformer["cells"]):

    source = "".join(cell.get("source", []))

    if "pop_zonal_stats_df" in source:

        print("=" * 80)
        print("CELL:", i)
        print("=" * 80)
        print(source)
        print()

================================================================================
CELL: 21
================================================================================
# TOTAL POPULATION IN EACH URBAN AREA
import rasterio
import rasterstats

worldpop_raster = rasterio.open('/home/krishna/IDS-DRR-Data-Pipeline/Sources/WORLDPOP/data/population_counts/assam_ppp_2020_UNadj.tif')
worldpop_raster_array = worldpop_raster.read(1)

sum_dicts = rasterstats.zonal_stats(assam_urban_shapes.to_crs(worldpop_raster.crs),
                                     worldpop_raster_array,
                                     affine= worldpop_raster.transform,
                                     stats= ['sum'],
                                     nodata=worldpop_raster.nodata,
                                     geojson_out = True)

dfs = []
for rc in sum_dicts:
    dfs.append(pd.DataFrame([rc['properties']]))

pop_zonal_stats_df = pd.concat(dfs).reset_index(drop=True)
pop_zonal_stats_df = pop_zonal_stats_df.rename(columns={'sum':'sum_population'})

================================================================================
CELL: 22
================================================================================
# Divide population by 4.3 for households
pop_zonal_stats_df['urban_hhd'] = pop_zonal_stats_df['sum_population']/4.3

================================================================================
CELL: 23
================================================================================
urban_hhd = pop_zonal_stats_df.groupby('object_id')[['urban_hhd']].sum().reset_index()
urban_hhd

In [51]:
# Find every cell that uses urban_hhd

for i, cell in enumerate(transformer["cells"]):

    source = "".join(cell.get("source", []))

    if "urban_hhd" in source:

        print("=" * 80)
        print("CELL:", i)
        print("=" * 80)
        print(source)
        print()

================================================================================
CELL: 22
================================================================================
# Divide population by 4.3 for households
pop_zonal_stats_df['urban_hhd'] = pop_zonal_stats_df['sum_population']/4.3

================================================================================
CELL: 23
================================================================================
urban_hhd = pop_zonal_stats_df.groupby('object_id')[['urban_hhd']].sum().reset_index()
urban_hhd

================================================================================
CELL: 24
================================================================================
urban_hhd['urban_electricity'] = urban_hhd['urban_hhd']*20

================================================================================
CELL: 25
================================================================================
urban_hhd['urban_tele'] = urban_hhd['urban_hhd']*3

================================================================================
CELL: 26
================================================================================
urban_hhd['urban_hhd_pipe'] = urban_hhd['urban_hhd']*0.1873

================================================================================
CELL: 27
================================================================================
urban_hhd['urban_no_sanitation'] = urban_hhd['urban_hhd']*0.063

================================================================================
CELL: 37
================================================================================
total_hhd = urban_hhd.merge(rural_hhd, how='outer', on='object_id')
total_hhd

================================================================================
CELL: 38
================================================================================
total_hhd = total_hhd.fillna(0)
total_hhd['total_hhd']=total_hhd['rural_hhd']+total_hhd['urban_hhd']

================================================================================
CELL: 46
================================================================================
rc_electricity = elect_df.merge(urban_hhd, on='object_id', how='outer')

================================================================================
CELL: 49
================================================================================
rc_electricity['total_hhd'] = rc_electricity['rural_hhd'] + rc_electricity['urban_hhd']

================================================================================
CELL: 58
================================================================================
rc_tele = telephone_df.merge(urban_hhd[['object_id', 'urban_hhd','urban_tele']], on='object_id', how='outer')

================================================================================
CELL: 61
================================================================================
rc_tele['total_hhd'] = rc_tele['rural_hhd'] + rc_tele['urban_hhd']

================================================================================
CELL: 67
================================================================================
pipe_df = pipe_df.merge(urban_hhd[['object_id','urban_hhd_pipe']], on='object_id', how='outer')

================================================================================
CELL: 69
================================================================================
pipe_df['rc_piped_hhds'] = pipe_df['urban_hhd_pipe'] + pipe_df['total_hhd_having_piped_water_connection']

================================================================================
CELL: 76
================================================================================
nosanitation_df = nosanitation_df.merge(urban_hhd[['object_id','urban_no_sanitation']], on='object_id', how='outer')

In [52]:
# Create a compact overview of all variables before making target decisions

column_overview = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing": df.isna().sum().values,
    "unique": df.nunique().values
})

print(column_overview.to_string(index=False))

                                      column   dtype  missing  unique
                                   object_id  object        0     180
                                    district  object        0      35
                                     rc_area   int64        0     169
                                  timeperiod  object        0      62
                  total_tender_awarded_value float64        0     379
               erosion_tenders_awarded_value float64        0      95
                  SOPD_tenders_awarded_value float64        0     122
                SDRF_sanctions_awarded_value float64        0     111
                  SDRF_tenders_awarded_value float64        0      74
                  RIDF_tenders_awarded_value float64        0      97
                  LTIF_tenders_awarded_value float64        0       1
                  CIDF_tenders_awarded_value float64        0       3
 Preparedness Measures_tenders_awarded_value float64        0     373
    Immediate Measures_tenders_awarded_value float64        0     103
                Others_tenders_awarded_value float64        0     232
Repair and Restoration_tenders_awarded_value float64        0     168
                    Total_Animal_Washed_Away float64        0      48
                       Total_Animal_Affected float64        0     437
                   Population_affected_Total float64        0     808
                                   Crop_Area float64        0     816
                                   Male_Camp float64        0     129
                                 Female_Camp float64        0     130
                               Children_Camp float64        0     118
                   Total_House_Fully_Damaged float64        0      78
                             Human_Live_Lost   int64        0      11
                    Human_Live_Lost_Children float64        0       6
                      Human_Live_Lost_Female float64        0       4
                        Human_Live_Lost_Male float64        0       7
                        Embankments affected float64        0      15
                                       Roads float64        0      71
                                      Bridge float64        0      13
                         Embankment breached float64        0      13
                                    max_rain float64        0    4309
                                   mean_rain float64        0   10030
                                    sum_rain float64        0   10370
                                   mean_ndvi float64        0    3802
                                   mean_ndbi float64        0    3622
                                       count float64        0    1438
                              inundation_pct float64        0    2088
                   inundation_intensity_mean float64        0    2087
           inundation_intensity_mean_nonzero float64        0    1290
                    inundation_intensity_sum float64        0    2015
                             riverlevel_mean float64        0    1899
                              riverlevel_min float64        0    1552
                              riverlevel_max float64        0    1633
                     total_expenditure_value float64        0     154
                      SDRF_expenditure_value float64        0     136
        Immediate Measures_expenditure_value float64        0     146
                    Others_expenditure_value float64        0      11
    Repair and Restoration_expenditure_value float64        0      11
                                Relief Camps float64        0      68
                              Relief Centers float64        0      98
                              Relief Inmates float64        0     322
                         Relief_Camp_inmates   int64        0     132
                              mean_sex_ratio float64        0    1080
                         sum_aged_population float64        0    1080
                        sum_young_population float64        0    1080
                              sum_population float64        0    1080
                                       water float64        0     538
                                       trees float64        0     541
                          flooded_vegetation float64        0     356
                                       crops float64        0     541
                                  built_area float64        0     541
                                 bare_ground float64        0     451
                                      clouds float64        0      11
                                   rangeland float64        0     517
                               schools_count   int64        0     156
                        health_centres_count   int64        0      49
                                 rail_length float64        0     119
                                  rail_count float64        0      31
                                 road_length float64        0     180
                                     mean_cn float64        0     180
                              elevation_mean float64        0     180
                                  slope_mean float64        0     180
                                  revenue_ci  object        0     159
                                      dtname  object        0      36
                                    dtcode11  object        0      36
                        net_sown_area_in_hac float64        0     178
                             avg_electricity float64        0     178
                                    avg_tele float64        0       2
                           rc_piped_hhds_pct float64        0     171
                    rc_nosanitation_hhds_pct float64        0     179
                                   total_hhd float64        0     177
                         distance_from_river float64        0     180
                            drainage_density float64        0     143
                      affected_to_population float64        0     853

In [53]:
# Search the current notebook for terms related to the project's objective

keywords = [
    "target",
    "predict",
    "prediction",
    "objective",
    "flood impact",
    "affected population",
    "machine learning",
    "model"
]

for i, code in enumerate(In):
    code_lower = code.lower()

    if any(keyword in code_lower for keyword in keywords):
        print("\n" + "="*80)
        print("CELL:", i)
        print("="*80)
        print(code[:3000])

================================================================================
CELL: 1
================================================================================
# Export baseline dataset with temporal and geographic metadata
# object_id and timeperiod are retained for validation/grouping only.
# They are NOT model features.

baseline_modeling_dataset_with_metadata = model_df[
    ["object_id", "timeperiod"] + baseline_features + ["next_month_impact"]
].copy()

baseline_modeling_dataset_with_metadata.to_csv(
    "baseline_modeling_dataset_with_metadata.csv",
    index=False
)

print("=" * 80)
print("BASELINE MODELLING DATASET WITH METADATA EXPORTED")
print("=" * 80)

print("File:", "baseline_modeling_dataset_with_metadata.csv")
print("Shape:", baseline_modeling_dataset_with_metadata.shape)

print("\nMetadata columns:")
print(["object_id", "timeperiod"])

print("\nNumber of model features:", len(baseline_features))
print("Target:", "next_month_impact")

print("\nMissing values:")
print(baseline_modeling_dataset_with_metadata.isnull().sum().sum())

print("\nFirst 5 rows:")
display(baseline_modeling_dataset_with_metadata.head())

================================================================================
CELL: 38
================================================================================
# Inspect the two variables that may be used to construct the target

print("Population_affected_Total")
print(df["Population_affected_Total"].describe())
print("\nMissing values:", df["Population_affected_Total"].isna().sum())

print("\n" + "="*60)

print("sum_population")
print(df["sum_population"].describe())
print("\nMissing values:", df["sum_population"].isna().sum())

================================================================================
CELL: 39
================================================================================
# Temporarily calculate the proposed affected population ratio
affected_ratio = (
    df["Population_affected_Total"] / df["sum_population"]
)

print("Number of observations:", len(affected_ratio))

print("\nNon-zero affected population:")
print((df["Population_affected_Total"] > 0).sum())

print("\nZero affected population:")
print((df["Population_affected_Total"] == 0).sum())

print("\nProposed ratio statistics:")
print(affected_ratio.describe())

print("\nRatios greater than 1:")
print((affected_ratio > 1).sum())

print("\nMaximum ratio:")
print(affected_ratio.max())

================================================================================
CELL: 40
================================================================================
# Find observations where affected population exceeds total population

invalid_ratio = df[
    df["Population_affected_Total"] > df["sum_population"]
].copy()

print("Number of observations with ratio > 1:", len(invalid_ratio))

print("\nRelevant columns:")
print(
    invalid_ratio[
        [
            "object_id",
            "district",
            "revenue_ci",
            "dtname",
            "dtcode11",
            "timeperiod",
            "Population_affected_Total",
            "sum_population"
        ]
    ].to_string(index=False)
)

================================================================================
CELL: 43
================================================================================
# Compare affected population with the annual population estimate

print("Affected population / population ratio by year:\n")

# Create the ratio if it does not already exist
if "affected_to_population" not in df.columns:
    df["affected_to_population"] = (
        df["Population_affected_Total"] /
        df["sum_population"].replace(0, np.nan)
    )

year_ratio = (
    df.groupby(df["timeperiod"].astype(str).str[:4])["affected_to_population"]
      .agg([
          ("mean", "mean"),
          ("median", "median"),
          ("max", "max"),
          ("nonzero", lambda x: (x > 0).sum()),
          ("above_1", lambda x: (x > 1).sum())
      ])
)

print(year_ratio)

================================================================================
CELL: 45
================================================================================
import json

rdls_path = os.path.join(
    source_folder,
    "Sources",
    "DRIMS",
    "metadata",
    "rdls.json"
)

with open(rdls_path, "r", errors="ignore") as f:
    rdls = json.load(f)

print(type(rdls))

# Search recursively for our variables
def find_variable(obj, target_names, path="root"):
    if isinstance(obj, dict):
        for key, value in obj.items():
            current_path = f"{path}.{key}"

            if str(key).lower() in [x.lower() for x in target_names]:
                print("\nFOUND KEY:", current_path)
                print(value)

            find_variable(value, target_names, current_path)

    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            find_variable(item, target_names, f"{path}[{i}]")

find_variable(
    rdls,
    ["Population_affected_Total", "sum_population"]
)

================================================================================
CELL: 52
================================================================================
# Create a compact overview of all variables before making target decisions

column_overview = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing": df.isna().sum().values,
    "unique": df.nunique().values
})

print(column_overview.to_string(index=False))

================================================================================
CELL: 53
================================================================================
# Search the current notebook for terms related to the project's objective

keywords = [
    "target",
    "predict",
    "prediction",
    "objective",
    "flood impact",
    "affected population",
    "machine learning",
    "model"
]

for i, code in enumerate(In):
    code_lower = code.lower()

    if any(keyword in code_lower for keyword in keywords):
        print("\n" + "="*80)
        print("CELL:", i)
        print("="*80)
        print(code[:3000])

In [54]:
# Examine temporal coverage of important hazard, exposure and impact variables

important_vars = [
    "Population_affected_Total",
    "max_rain",
    "mean_rain",
    "sum_rain",
    "inundation_pct",
    "inundation_intensity_mean",
    "riverlevel_mean",
    "riverlevel_max",
    "sum_population",
    "Human_Live_Lost",
    "Relief Camps",
    "total_expenditure_value"
]

print("Temporal coverage of selected variables:\n")

for col in important_vars:
    if col in df.columns:
        print(
            f"{col:40s} "
            f"non-zero = {(df[col] != 0).sum():5d} | "
            f"unique = {df[col].nunique():5d}"
        )

print("\nTimeperiod coverage:")
print(df["timeperiod"].value_counts().sort_index().to_string())

Temporal coverage of selected variables:

Population_affected_Total                non-zero =   877 | unique =   808
max_rain                                 non-zero = 10370 | unique =  4309
mean_rain                                non-zero = 10370 | unique = 10030
sum_rain                                 non-zero = 10370 | unique = 10370
inundation_pct                           non-zero =  2087 | unique =  2088
inundation_intensity_mean                non-zero =  2087 | unique =  2087
riverlevel_mean                          non-zero =  1898 | unique =  1899
riverlevel_max                           non-zero =  1898 | unique =  1633
sum_population                           non-zero = 11160 | unique =  1080
Human_Live_Lost                          non-zero =   180 | unique =    11
Relief Camps                             non-zero =   348 | unique =    68
total_expenditure_value                  non-zero =   157 | unique =   154

Timeperiod coverage:
timeperiod
2021_04    180
2021_05    180
2021_06    180
2021_07    180
2021_08    180
2021_09    180
2021_10    180
2021_11    180
2021_12    180
2022_01    180
2022_02    180
2022_03    180
2022_04    180
2022_05    180
2022_06    180
2022_07    180
2022_08    180
2022_09    180
2022_10    180
2022_11    180
2022_12    180
2023_01    180
2023_02    180
2023_03    180
2023_04    180
2023_05    180
2023_06    180
2023_07    180
2023_08    180
2023_09    180
2023_10    180
2023_11    180
2023_12    180
2024_01    180
2024_02    180
2024_03    180
2024_04    180
2024_05    180
2024_06    180
2024_07    180
2024_08    180
2024_09    180
2024_10    180
2024_11    180
2024_12    180
2025_01    180
2025_02    180
2025_03    180
2025_04    180
2025_05    180
2025_06    180
2025_07    180
2025_08    180
2025_09    180
2025_10    180
2025_11    180
2025_12    180
2026_01    180
2026_02    180
2026_03    180
2026_04    180
2026_05    180

In [55]:
# Check temporal persistence of population impact

temp_df = df[
    ["object_id", "timeperiod", "Population_affected_Total"]
].copy()

# Convert timeperiod to proper datetime
temp_df["date"] = pd.to_datetime(
    temp_df["timeperiod"],
    format="%Y_%m"
)

# Sort spatially and temporally
temp_df = temp_df.sort_values(
    ["object_id", "date"]
)

# Binary impact indicator
temp_df["impact"] = (
    temp_df["Population_affected_Total"] > 0
).astype(int)

# Previous month's impact for the same Revenue Circle
temp_df["previous_impact"] = (
    temp_df.groupby("object_id")["impact"]
    .shift(1)
)

# Cases where current month has impact
current_impact = temp_df["impact"] == 1

# Consecutive impact:
# current month affected AND previous month affected
consecutive = (
    current_impact &
    (temp_df["previous_impact"] == 1)
)

print("Total non-zero impact observations:",
      current_impact.sum())

print("Impact observations preceded by another impacted month:",
      consecutive.sum())

print(
    "Percentage of impacted observations preceded by impact:",
    round(
        100 * consecutive.sum() / current_impact.sum(),
        2
    ),
    "%"
)

Total non-zero impact observations: 877
Impact observations preceded by another impacted month: 389
Percentage of impacted observations preceded by impact: 44.36 %

In [56]:
# Analyze month-to-month transitions in population impact

transition_df = temp_df.copy()

# Remove the first month for each Revenue Circle
transition_df = transition_df.dropna(
    subset=["previous_impact"]
)

# Create transition labels
transition_df["transition"] = (
    transition_df["previous_impact"].astype(int).astype(str)
    + " -> "
    + transition_df["impact"].astype(int).astype(str)
)

print("Month-to-month impact transitions:\n")
print(
    transition_df["transition"]
    .value_counts()
    .sort_index()
)

print("\n" + "="*70)

# Conditional probability of current impact
# given previous month's state

prob_previous_impact = transition_df.loc[
    transition_df["previous_impact"] == 1,
    "impact"
].mean()

prob_previous_no_impact = transition_df.loc[
    transition_df["previous_impact"] == 0,
    "impact"
].mean()

print(
    "P(Current impact | Previous month impacted):",
    round(prob_previous_impact, 4)
)

print(
    "P(Current impact | Previous month not impacted):",
    round(prob_previous_no_impact, 4)
)

print("\nDifference:")
print(
    round(
        prob_previous_impact - prob_previous_no_impact,
        4
    )
)

Month-to-month impact transitions:

transition
0 -> 0    9619
0 -> 1     488
1 -> 0     484
1 -> 1     389
Name: count, dtype: int64

======================================================================
P(Current impact | Previous month impacted): 0.4456
P(Current impact | Previous month not impacted): 0.0483

Difference:
0.3973

In [57]:


rain_df = df[
    [
        "object_id",
        "timeperiod",
        "Population_affected_Total",
        "sum_rain",
        "max_rain",
        "mean_rain"
    ]
].copy()

# Convert timeperiod to datetime
rain_df["date"] = pd.to_datetime(
    rain_df["timeperiod"],
    format="%Y_%m"
)

# Sort by Revenue Circle and time
rain_df = rain_df.sort_values(
    ["object_id", "date"]
)

# Binary impact
rain_df["impact"] = (
    rain_df["Population_affected_Total"] > 0
).astype(int)

# Previous-month rainfall
for col in ["sum_rain", "max_rain", "mean_rain"]:
    rain_df[f"previous_{col}"] = (
        rain_df.groupby("object_id")[col].shift(1)
    )

# Remove first month of each spatial unit
rain_df = rain_df.dropna(
    subset=[
        "previous_sum_rain",
        "previous_max_rain",
        "previous_mean_rain"
    ]
)

print("Current-month rainfall statistics by impact:\n")

print(
    rain_df.groupby("impact")[
        ["sum_rain", "max_rain", "mean_rain"]
    ].mean()
)

print("\n" + "="*70)

print("Previous-month rainfall statistics by CURRENT impact:\n")

print(
    rain_df.groupby("impact")[
        [
            "previous_sum_rain",
            "previous_max_rain",
            "previous_mean_rain"
        ]
    ].mean()
)

Current-month rainfall statistics by impact:

          sum_rain  max_rain  mean_rain
impact
0        87.461229  0.291048   0.241991
1       294.793810  0.807616   0.672892

======================================================================
Previous-month rainfall statistics by CURRENT impact:

        previous_sum_rain  previous_max_rain  previous_mean_rain
impact
0               87.479225           0.292797            0.243158
1              280.236577           0.740349            0.620010

In [58]:


spatial_impact = (
    df.groupby("object_id")
      .agg(
          total_months=("Population_affected_Total", "size"),
          impacted_months=(
              "Population_affected_Total",
              lambda x: (x > 0).sum()
          ),
          max_affected_population=(
              "Population_affected_Total",
              "max"
          )
      )
)

spatial_impact["impact_rate"] = (
    spatial_impact["impacted_months"]
    / spatial_impact["total_months"]
)

print("Impact-rate statistics across Revenue Circles:\n")
print(
    spatial_impact["impact_rate"].describe()
)

print("\n" + "="*70)

print("Revenue Circles with highest impact rates:\n")

print(
    spatial_impact
    .sort_values("impact_rate", ascending=False)
    .head(15)
)

print("\n" + "="*70)

print("Revenue Circles with zero reported impact:\n")

print(
    (spatial_impact["impacted_months"] == 0).sum(),
    "out of",
    len(spatial_impact)
)

Impact-rate statistics across Revenue Circles:

count    180.000000
mean       0.078584
std        0.071910
min        0.000000
25%        0.000000
50%        0.064516
75%        0.112903
max        0.370968
Name: impact_rate, dtype: float64

======================================================================
Revenue Circles with highest impact rates:

              total_months  impacted_months  max_affected_population  \
object_id
18-308-00150            62               23                  15464.0
18-308-00151            62               20                  46684.0
18-310-00160            62               17                  12152.0
18-756-00250            62               17                  41310.0
18-308-00152            62               16                  62335.0
18-307-00142            62               16                  28928.0
18-756-00251            62               15                  38763.0
18-307-00145            62               14                  89795.0
18-307-00141            62               14                  34522.0
18-325-00269            62               13                 125007.0
18-309-00156            62               12                  14829.0
18-311-00166            62               12                  29893.0
18-312-00169            62               12                  12291.0
18-313-00172            62               12                  85761.0
18-325-00239            62               12                 154678.0

              impact_rate
object_id
18-308-00150     0.370968
18-308-00151     0.322581
18-310-00160     0.274194
18-756-00250     0.274194
18-308-00152     0.258065
18-307-00142     0.258065
18-756-00251     0.241935
18-307-00145     0.225806
18-307-00141     0.225806
18-325-00269     0.209677
18-309-00156     0.193548
18-311-00166     0.193548
18-312-00169     0.193548
18-313-00172     0.193548
18-325-00239     0.193548

======================================================================
Revenue Circles with zero reported impact:

49 out of 180

In [59]:


# Sort observations chronologically within each Revenue Circle
df_sorted = df.sort_values(
    ["object_id", "timeperiod"]
).copy()

# Current-month impact indicator
df_sorted["current_impact"] = (
    df_sorted["Population_affected_Total"] > 0
).astype(int)

# Next month's impact for the same Revenue Circle
df_sorted["next_month_impact"] = (
    df_sorted
    .groupby("object_id")["current_impact"]
    .shift(-1)
)

# Remove the final month of each Revenue Circle
prediction_data = df_sorted.dropna(
    subset=["next_month_impact"]
).copy()

prediction_data["next_month_impact"] = (
    prediction_data["next_month_impact"].astype(int)
)

print("Observations available for one-month-ahead analysis:",
      len(prediction_data))

print("\nNext-month impact distribution:")
print(
    prediction_data["next_month_impact"]
    .value_counts()
)

print("\nNext-month impact rate:")
print(
    prediction_data["next_month_impact"].mean()
)

print("\n" + "="*70)

# Relationship between current and next-month impact
transition = pd.crosstab(
    prediction_data["current_impact"],
    prediction_data["next_month_impact"]
)

print("Current impact → Next-month impact:")
print(transition)

print("\n" + "="*70)

print(
    "P(Next-month impact | Current impact):",
    prediction_data.loc[
        prediction_data["current_impact"] == 1,
        "next_month_impact"
    ].mean()
)

print(
    "P(Next-month impact | Current no impact):",
    prediction_data.loc[
        prediction_data["current_impact"] == 0,
        "next_month_impact"
    ].mean()
)

Observations available for one-month-ahead analysis: 10980

Next-month impact distribution:
next_month_impact
0    10103
1      877
Name: count, dtype: int64

Next-month impact rate:
0.07987249544626594

======================================================================
Current impact → Next-month impact:
next_month_impact     0    1
current_impact
0                  9619  488
1                   484  389

======================================================================
P(Next-month impact | Current impact): 0.44558991981672397
P(Next-month impact | Current no impact): 0.048283367962798064

In [60]:


rainfall_prediction = prediction_data.groupby(
    "next_month_impact"
)[
    [
        "sum_rain",
        "max_rain",
        "mean_rain"
    ]
].mean()

print("Current-month rainfall by NEXT-month impact:\n")
print(rainfall_prediction)

print("\n" + "="*70)

# Compare rainfall between the two groups
for col in ["sum_rain", "max_rain", "mean_rain"]:

    impact_mean = prediction_data.loc[
        prediction_data["next_month_impact"] == 1,
        col
    ].mean()

    no_impact_mean = prediction_data.loc[
        prediction_data["next_month_impact"] == 0,
        col
    ].mean()

    print(f"\n{col}")

    print("  Next month impacted     :", impact_mean)
    print("  Next month not impacted :", no_impact_mean)

    if no_impact_mean != 0:
        print(
            "  Ratio:",
            impact_mean / no_impact_mean
        )

Current-month rainfall by NEXT-month impact:

                     sum_rain  max_rain  mean_rain
next_month_impact
0                   87.479225  0.292797   0.243158
1                  280.236577  0.740349   0.620010

======================================================================

sum_rain
  Next month impacted     : 280.2365773734885
  Next month not impacted : 87.47922474759167
  Ratio: 3.2034643446151883

max_rain
  Next month impacted     : 0.7403486198540049
  Next month not impacted : 0.29279694366247355
  Ratio: 2.528539439631084

mean_rain
  Next month impacted     : 0.6200099748691998
  Next month not impacted : 0.2431583138402304
  Ratio: 2.549820177140164

In [61]:

# Define a temporary binary flood-impact indicator

df["impact"] = (
    df["Population_affected_Total"] > 0
).astype(int)

print("Impact target created.")
print()

print("Impact distribution:")
print(df["impact"].value_counts())

print("\nImpact proportion:")
print(df["impact"].value_counts(normalize=True))

print("\nNon-zero affected population:")
print((df["Population_affected_Total"] > 0).sum())

print("Zero affected population:")
print((df["Population_affected_Total"] == 0).sum())

Impact target created.

Impact distribution:
impact
0    10283
1      877
Name: count, dtype: int64

Impact proportion:
impact
0    0.921416
1    0.078584
Name: proportion, dtype: float64

Non-zero affected population:
877
Zero affected population:
10283

In [62]:

# Group variables according to their likely role in the prediction problem

target_related = [
    "Population_affected_Total",
    "affected_to_population",
    "impact"
]

environmental_variables = [
    "max_rain",
    "mean_rain",
    "sum_rain",
    "mean_ndvi",
    "mean_ndbi",
    "inundation_pct",
    "inundation_intensity_mean",
    "inundation_intensity_mean_nonzero",
    "inundation_intensity_sum",
    "riverlevel_mean",
    "riverlevel_min",
    "riverlevel_max",
    "water",
    "trees",
    "flooded_vegetation",
    "crops",
    "built_area",
    "bare_ground",
    "clouds",
    "rangeland"
]

exposure_variables = [
    "sum_population",
    "sum_aged_population",
    "sum_young_population",
    "mean_sex_ratio",
    "total_hhd",
    "net_sown_area_in_hac",
    "schools_count",
    "health_centres_count",
    "road_length",
    "rail_length",
    "rail_count",
    "distance_from_river",
    "drainage_density",
    "elevation_mean",
    "slope_mean",
    "mean_cn"
]

response_variables = [
    "Relief Camps",
    "Relief Centers",
    "Relief Inmates",
    "Relief_Camp_inmates",
    "total_expenditure_value",
    "SDRF_expenditure_value",
    "Immediate Measures_expenditure_value",
    "Others_expenditure_value",
    "Repair and Restoration_expenditure_value"
]

impact_damage_variables = [
    "Total_Animal_Washed_Away",
    "Total_Animal_Affected",
    "Crop_Area",
    "Male_Camp",
    "Female_Camp",
    "Children_Camp",
    "Total_House_Fully_Damaged",
    "Human_Live_Lost",
    "Human_Live_Lost_Children",
    "Human_Live_Lost_Female",
    "Human_Live_Lost_Male",
    "Embankments affected",
    "Roads",
    "Bridge",
    "Embankment breached"
]

tender_variables = [
    "total_tender_awarded_value",
    "erosion_tenders_awarded_value",
    "SOPD_tenders_awarded_value",
    "SDRF_sanctions_awarded_value",
    "SDRF_tenders_awarded_value",
    "RIDF_tenders_awarded_value",
    "LTIF_tenders_awarded_value",
    "CIDF_tenders_awarded_value",
    "Preparedness Measures_tenders_awarded_value",
    "Immediate Measures_tenders_awarded_value",
    "Others_tenders_awarded_value",
    "Repair and Restoration_tenders_awarded_value"
]

static_or_geographic = [
    "rc_area",
    "revenue_ci",
    "dtname",
    "dtcode11",
    "object_id",
    "district"
]

print("TARGET / DERIVED")
print(target_related)

print("\nENVIRONMENTAL")
print(environmental_variables)

print("\nEXPOSURE / VULNERABILITY")
print(exposure_variables)

print("\nRESPONSE")
print(response_variables)

print("\nDAMAGE / IMPACT")
print(impact_damage_variables)

print("\nTENDERS / INTERVENTIONS")
print(tender_variables)

print("\nSTATIC / GEOGRAPHIC")
print(static_or_geographic)

TARGET / DERIVED
['Population_affected_Total', 'affected_to_population', 'impact']

ENVIRONMENTAL
['max_rain', 'mean_rain', 'sum_rain', 'mean_ndvi', 'mean_ndbi', 'inundation_pct', 'inundation_intensity_mean', 'inundation_intensity_mean_nonzero', 'inundation_intensity_sum', 'riverlevel_mean', 'riverlevel_min', 'riverlevel_max', 'water', 'trees', 'flooded_vegetation', 'crops', 'built_area', 'bare_ground', 'clouds', 'rangeland']

EXPOSURE / VULNERABILITY
['sum_population', 'sum_aged_population', 'sum_young_population', 'mean_sex_ratio', 'total_hhd', 'net_sown_area_in_hac', 'schools_count', 'health_centres_count', 'road_length', 'rail_length', 'rail_count', 'distance_from_river', 'drainage_density', 'elevation_mean', 'slope_mean', 'mean_cn']

RESPONSE
['Relief Camps', 'Relief Centers', 'Relief Inmates', 'Relief_Camp_inmates', 'total_expenditure_value', 'SDRF_expenditure_value', 'Immediate Measures_expenditure_value', 'Others_expenditure_value', 'Repair and Restoration_expenditure_value']

DAMAGE / IMPACT
['Total_Animal_Washed_Away', 'Total_Animal_Affected', 'Crop_Area', 'Male_Camp', 'Female_Camp', 'Children_Camp', 'Total_House_Fully_Damaged', 'Human_Live_Lost', 'Human_Live_Lost_Children', 'Human_Live_Lost_Female', 'Human_Live_Lost_Male', 'Embankments affected', 'Roads', 'Bridge', 'Embankment breached']

TENDERS / INTERVENTIONS
['total_tender_awarded_value', 'erosion_tenders_awarded_value', 'SOPD_tenders_awarded_value', 'SDRF_sanctions_awarded_value', 'SDRF_tenders_awarded_value', 'RIDF_tenders_awarded_value', 'LTIF_tenders_awarded_value', 'CIDF_tenders_awarded_value', 'Preparedness Measures_tenders_awarded_value', 'Immediate Measures_tenders_awarded_value', 'Others_tenders_awarded_value', 'Repair and Restoration_tenders_awarded_value']

STATIC / GEOGRAPHIC
['rc_area', 'revenue_ci', 'dtname', 'dtcode11', 'object_id', 'district']

In [63]:

# Examine temporal variability of candidate predictor variables

candidate_variables = (
    environmental_variables
    + exposure_variables
    + response_variables
    + impact_damage_variables
    + tender_variables
)

temporal_variability = []

for col in candidate_variables:
    if col in df.columns:
        variability = df.groupby("object_id")[col].nunique()

        temporal_variability.append({
            "variable": col,
            "min_unique_per_RC": variability.min(),
            "median_unique_per_RC": variability.median(),
            "max_unique_per_RC": variability.max(),
            "overall_unique": df[col].nunique(),
            "nonzero": (df[col] != 0).sum()
        })

temporal_variability = pd.DataFrame(temporal_variability)

print(temporal_variability.to_string(index=False))

                                    variable  min_unique_per_RC  median_unique_per_RC  max_unique_per_RC  overall_unique  nonzero
                                    max_rain                 53                  58.0                 62            4309    10370
                                   mean_rain                 53                  58.0                 62           10030    10370
                                    sum_rain                 53                  58.0                 62           10370    10370
                                   mean_ndvi                 16                  21.0                 27            3802    11160
                                   mean_ndbi                 15                  20.0                 26            3622    11160
                              inundation_pct                  3                  13.0                 17            2088     2087
                   inundation_intensity_mean                  3                  13.0                 17            2087     2087
           inundation_intensity_mean_nonzero                  3                  12.0                 16            1290     2087
                    inundation_intensity_sum                  3                  13.0                 17            2015     2087
                             riverlevel_mean                  1                   1.0                 39            1899     1898
                              riverlevel_min                  1                   1.0                 39            1552     1881
                              riverlevel_max                  1                   1.0                 39            1633     1898
                                       water                  2                   4.0                  4             538     5907
                                       trees                  4                   4.0                  4             541     5940
                          flooded_vegetation                  1                   4.0                  4             356     3906
                                       crops                  4                   4.0                  4             541     5940
                                  built_area                  4                   4.0                  4             541     5940
                                 bare_ground                  1                   4.0                  4             451     4947
                                      clouds                  1                   1.0                  2              11       93
                                   rangeland                  1                   4.0                  4             517     5673
                              sum_population                  6                   6.0                  6            1080    11160
                         sum_aged_population                  6                   6.0                  6            1080    11160
                        sum_young_population                  6                   6.0                  6            1080    11160
                              mean_sex_ratio                  6                   6.0                  6            1080    11160
                                   total_hhd                  1                   1.0                  1             177    10912
                        net_sown_area_in_hac                  1                   1.0                  1             178    11160
                               schools_count                  1                   1.0                  1             156    11160
                        health_centres_count                  1                   1.0                  1              49    11160
                                 road_length                  1                   1.0                  1             180    11160
                                 rail_length                  1                   1.0                  1             119     7316
                                  rail_count                  1                   1.0                  1              31     7316
                         distance_from_river                  1                   1.0                  1             180    11160
                            drainage_density                  1                   1.0                  1             143    11160
                              elevation_mean                  1                   1.0                  1             180    11160
                                  slope_mean                  1                   1.0                  1             180    11160
                                     mean_cn                  1                   1.0                  1             180    11160
                                Relief Camps                  1                   2.0                  8              68      348
                              Relief Centers                  1                   4.0                 13              98      671
                              Relief Inmates                  1                   3.0                 10             322      347
                         Relief_Camp_inmates                  1                   1.0                  5             132      136
                     total_expenditure_value                  1                   1.0                 14             154      157
                      SDRF_expenditure_value                  1                   1.0                 14             136      138
        Immediate Measures_expenditure_value                  1                   1.0                 14             146      149
                    Others_expenditure_value                  1                   1.0                  3              11       10
    Repair and Restoration_expenditure_value                  1                   1.0                  3              11       10
                    Total_Animal_Washed_Away                  1                   1.0                  4              48       71
                       Total_Animal_Affected                  1                   3.0                 12             437      444
                                   Crop_Area                  1                   7.0                 19             816     1081
                                   Male_Camp                  1                   1.0                  5             129      135
                                 Female_Camp                  1                   1.0                  5             130      136
                               Children_Camp                  1                   1.0                  4             118      135
                   Total_House_Fully_Damaged                  1                   1.5                  6              78      159
                             Human_Live_Lost                  1                   2.0                  5              11      180
                    Human_Live_Lost_Children                  1                   1.0                  4               6       53
                      Human_Live_Lost_Female                  1                   1.0                  3               4       15
                        Human_Live_Lost_Male                  1                   1.0                  4               7       88
                        Embankments affected                  1                   1.0                  6              15      173
                                       Roads                  1                   4.0                 13              71      678
                                      Bridge                  1                   1.0                  5              13      148
                         Embankment breached                  1                   1.0                  7              13      133
                  total_tender_awarded_value                  1                   1.0                 43             379      379
               erosion_tenders_awarded_value                  1                   1.0                 11              95       94
                  SOPD_tenders_awarded_value                  1                   1.0                 28             122      121
                SDRF_sanctions_awarded_value                  2                   5.0                  8             111      673
                  SDRF_tenders_awarded_value                  1                   1.0                 10              74       73
                  RIDF_tenders_awarded_value                  1                   1.0                 12              97       96
                  LTIF_tenders_awarded_value                  1                   1.0                  1               1        0
                  CIDF_tenders_awarded_value                  1                   1.0                  2               3        2
 Preparedness Measures_tenders_awarded_value                  1                   2.0                 21             373      373
    Immediate Measures_tenders_awarded_value                  1                   1.0                 16             103      102
                Others_tenders_awarded_value                  1                   1.0                 31             232      232
Repair and Restoration_tenders_awarded_value                  1                   1.0                 22             168      167

In [64]:

# Check when each important variable has observations

important_variables = [
    "Population_affected_Total",
    "max_rain",
    "mean_rain",
    "sum_rain",
    "inundation_pct",
    "inundation_intensity_mean",
    "riverlevel_mean",
    "riverlevel_max",
    "sum_population",
    "Human_Live_Lost",
    "Relief Camps",
    "total_expenditure_value"
]

availability = []

for col in important_variables:
    monthly = df.groupby("timeperiod")[col].apply(
        lambda x: (x != 0).sum()
    )

    for month, nonzero_count in monthly.items():
        availability.append({
            "variable": col,
            "timeperiod": month,
            "nonzero": nonzero_count
        })

availability_df = pd.DataFrame(availability)

print(availability_df.to_string(index=False))

                 variable timeperiod  nonzero
Population_affected_Total    2021_04        0
Population_affected_Total    2021_05        0
Population_affected_Total    2021_06       14
Population_affected_Total    2021_07        8
Population_affected_Total    2021_08       49
Population_affected_Total    2021_09       38
Population_affected_Total    2021_10        0
Population_affected_Total    2021_11        0
Population_affected_Total    2021_12        0
Population_affected_Total    2022_01        0
Population_affected_Total    2022_02        0
Population_affected_Total    2022_03        0
Population_affected_Total    2022_04        4
Population_affected_Total    2022_05       50
Population_affected_Total    2022_06      109
Population_affected_Total    2022_07       70
Population_affected_Total    2022_08       17
Population_affected_Total    2022_09        5
Population_affected_Total    2022_10        9
Population_affected_Total    2022_11        0
Population_affected_Total    2022_12        0
Population_affected_Total    2023_01        0
Population_affected_Total    2023_02        0
Population_affected_Total    2023_03        0
Population_affected_Total    2023_04        0
Population_affected_Total    2023_05        1
Population_affected_Total    2023_06       51
Population_affected_Total    2023_07       46
Population_affected_Total    2023_08       54
Population_affected_Total    2023_09       22
Population_affected_Total    2023_10        0
Population_affected_Total    2023_11        0
Population_affected_Total    2023_12        0
Population_affected_Total    2024_01        0
Population_affected_Total    2024_02        0
Population_affected_Total    2024_03        0
Population_affected_Total    2024_04        0
Population_affected_Total    2024_05        0
Population_affected_Total    2024_06       63
Population_affected_Total    2024_07       98
Population_affected_Total    2024_08       27
Population_affected_Total    2024_09        4
Population_affected_Total    2024_10        0
Population_affected_Total    2024_11        0
Population_affected_Total    2024_12        0
Population_affected_Total    2025_01        0
Population_affected_Total    2025_02        0
Population_affected_Total    2025_03        0
Population_affected_Total    2025_04        0
Population_affected_Total    2025_05       14
Population_affected_Total    2025_06       54
Population_affected_Total    2025_07       21
Population_affected_Total    2025_08       20
Population_affected_Total    2025_09       20
Population_affected_Total    2025_10        5
Population_affected_Total    2025_11        0
Population_affected_Total    2025_12        0
Population_affected_Total    2026_01        0
Population_affected_Total    2026_02        0
Population_affected_Total    2026_03        0
Population_affected_Total    2026_04        0
Population_affected_Total    2026_05        4
                 max_rain    2021_04      180
                 max_rain    2021_05      180
                 max_rain    2021_06      180
                 max_rain    2021_07      180
                 max_rain    2021_08      180
                 max_rain    2021_09      180
                 max_rain    2021_10      180
                 max_rain    2021_11      139
                 max_rain    2021_12      156
                 max_rain    2022_01      180
                 max_rain    2022_02      180
                 max_rain    2022_03      180
                 max_rain    2022_04      180
                 max_rain    2022_05      180
                 max_rain    2022_06      180
                 max_rain    2022_07      180
                 max_rain    2022_08      180
                 max_rain    2022_09      180
                 max_rain    2022_10      180
                 max_rain    2022_11       51
                 max_rain    2022_12      171
                 max_rain    2023_01       60
                 max_rain    2023_02      180
                 max_rain    2023_03      180
                 max_rain    2023_04      180
                 max_rain    2023_05      180
                 max_rain    2023_06      180
                 max_rain    2023_07      180
                 max_rain    2023_08      180
                 max_rain    2023_09      180
                 max_rain    2023_10      180
                 max_rain    2023_11      180
                 max_rain    2023_12      180
                 max_rain    2024_01      147
                 max_rain    2024_02      180
                 max_rain    2024_03      180
                 max_rain    2024_04      180
                 max_rain    2024_05      180
                 max_rain    2024_06      180
                 max_rain    2024_07      180
                 max_rain    2024_08      180
                 max_rain    2024_09      180
                 max_rain    2024_10      180
                 max_rain    2024_11      180
                 max_rain    2024_12       88
                 max_rain    2025_01      159
                 max_rain    2025_02      180
                 max_rain    2025_03      179
                 max_rain    2025_04      180
                 max_rain    2025_05      180
                 max_rain    2025_06      180
                 max_rain    2025_07      180
                 max_rain    2025_08      180
                 max_rain    2025_09      180
                 max_rain    2025_10      180
                 max_rain    2025_11      180
                 max_rain    2025_12       59
                 max_rain    2026_01       62
                 max_rain    2026_02       99
                 max_rain    2026_03      180
                 max_rain    2026_04      180
                 max_rain    2026_05      180
                mean_rain    2021_04      180
                mean_rain    2021_05      180
                mean_rain    2021_06      180
                mean_rain    2021_07      180
                mean_rain    2021_08      180
                mean_rain    2021_09      180
                mean_rain    2021_10      180
                mean_rain    2021_11      139
                mean_rain    2021_12      156
                mean_rain    2022_01      180
                mean_rain    2022_02      180
                mean_rain    2022_03      180
                mean_rain    2022_04      180
                mean_rain    2022_05      180
                mean_rain    2022_06      180
                mean_rain    2022_07      180
                mean_rain    2022_08      180
                mean_rain    2022_09      180
                mean_rain    2022_10      180
                mean_rain    2022_11       51
                mean_rain    2022_12      171
                mean_rain    2023_01       60
                mean_rain    2023_02      180
                mean_rain    2023_03      180
                mean_rain    2023_04      180
                mean_rain    2023_05      180
                mean_rain    2023_06      180
                mean_rain    2023_07      180
                mean_rain    2023_08      180
                mean_rain    2023_09      180
                mean_rain    2023_10      180
                mean_rain    2023_11      180
                mean_rain    2023_12      180
                mean_rain    2024_01      147
                mean_rain    2024_02      180
                mean_rain    2024_03      180
                mean_rain    2024_04      180
                mean_rain    2024_05      180
                mean_rain    2024_06      180
                mean_rain    2024_07      180
                mean_rain    2024_08      180
                mean_rain    2024_09      180
                mean_rain    2024_10      180
                mean_rain    2024_11      180
                mean_rain    2024_12       88
                mean_rain    2025_01      159
                mean_rain    2025_02      180
                mean_rain    2025_03      179
                mean_rain    2025_04      180
                mean_rain    2025_05      180
                mean_rain    2025_06      180
                mean_rain    2025_07      180
                mean_rain    2025_08      180
                mean_rain    2025_09      180
                mean_rain    2025_10      180
                mean_rain    2025_11      180
                mean_rain    2025_12       59
                mean_rain    2026_01       62
                mean_rain    2026_02       99
                mean_rain    2026_03      180
                mean_rain    2026_04      180
                mean_rain    2026_05      180
                 sum_rain    2021_04      180
                 sum_rain    2021_05      180
                 sum_rain    2021_06      180
                 sum_rain    2021_07      180
                 sum_rain    2021_08      180
                 sum_rain    2021_09      180
                 sum_rain    2021_10      180
                 sum_rain    2021_11      139
                 sum_rain    2021_12      156
                 sum_rain    2022_01      180
                 sum_rain    2022_02      180
                 sum_rain    2022_03      180
                 sum_rain    2022_04      180
                 sum_rain    2022_05      180
                 sum_rain    2022_06      180
                 sum_rain    2022_07      180
                 sum_rain    2022_08      180
                 sum_rain    2022_09      180
                 sum_rain    2022_10      180
                 sum_rain    2022_11       51
                 sum_rain    2022_12      171
                 sum_rain    2023_01       60
                 sum_rain    2023_02      180
                 sum_rain    2023_03      180
                 sum_rain    2023_04      180
                 sum_rain    2023_05      180
                 sum_rain    2023_06      180
                 sum_rain    2023_07      180
                 sum_rain    2023_08      180
                 sum_rain    2023_09      180
                 sum_rain    2023_10      180
                 sum_rain    2023_11      180
                 sum_rain    2023_12      180
                 sum_rain    2024_01      147
                 sum_rain    2024_02      180
                 sum_rain    2024_03      180
                 sum_rain    2024_04      180
                 sum_rain    2024_05      180
                 sum_rain    2024_06      180
                 sum_rain    2024_07      180
                 sum_rain    2024_08      180
                 sum_rain    2024_09      180
                 sum_rain    2024_10      180
                 sum_rain    2024_11      180
                 sum_rain    2024_12       88
                 sum_rain    2025_01      159
                 sum_rain    2025_02      180
                 sum_rain    2025_03      179
                 sum_rain    2025_04      180
                 sum_rain    2025_05      180
                 sum_rain    2025_06      180
                 sum_rain    2025_07      180
                 sum_rain    2025_08      180
                 sum_rain    2025_09      180
                 sum_rain    2025_10      180
                 sum_rain    2025_11      180
                 sum_rain    2025_12       59
                 sum_rain    2026_01       62
                 sum_rain    2026_02       99
                 sum_rain    2026_03      180
                 sum_rain    2026_04      180
                 sum_rain    2026_05      180
           inundation_pct    2021_04        0
           inundation_pct    2021_05        0
           inundation_pct    2021_06       67
           inundation_pct    2021_07      132
           inundation_pct    2021_08      103
           inundation_pct    2021_09       92
           inundation_pct    2021_10        0
           inundation_pct    2021_11        0
           inundation_pct    2021_12        0
           inundation_pct    2022_01        0
           inundation_pct    2022_02        0
           inundation_pct    2022_03        0
           inundation_pct    2022_04        0
           inundation_pct    2022_05      163
           inundation_pct    2022_06      171
           inundation_pct    2022_07      171
           inundation_pct    2022_08        0
           inundation_pct    2022_09        0
           inundation_pct    2022_10        0
           inundation_pct    2022_11        0
           inundation_pct    2022_12        0
           inundation_pct    2023_01        0
           inundation_pct    2023_02        0
           inundation_pct    2023_03        0
           inundation_pct    2023_04        0
           inundation_pct    2023_05        0
           inundation_pct    2023_06      158
           inundation_pct    2023_07      108
           inundation_pct    2023_08       80
           inundation_pct    2023_09        0
           inundation_pct    2023_10        0
           inundation_pct    2023_11        0
           inundation_pct    2023_12        0
           inundation_pct    2024_01        0
           inundation_pct    2024_02        0
           inundation_pct    2024_03        0
           inundation_pct    2024_04        0
           inundation_pct    2024_05       25
           inundation_pct    2024_06      140
           inundation_pct    2024_07      175
           inundation_pct    2024_08       86
           inundation_pct    2024_09        0
           inundation_pct    2024_10        0
           inundation_pct    2024_11        0
           inundation_pct    2024_12        0
           inundation_pct    2025_01        0
           inundation_pct    2025_02        0
           inundation_pct    2025_03        0
           inundation_pct    2025_04        0
           inundation_pct    2025_05        0
           inundation_pct    2025_06      167
           inundation_pct    2025_07      135
           inundation_pct    2025_08       40
           inundation_pct    2025_09       74
           inundation_pct    2025_10        0
           inundation_pct    2025_11        0
           inundation_pct    2025_12        0
           inundation_pct    2026_01        0
           inundation_pct    2026_02        0
           inundation_pct    2026_03        0
           inundation_pct    2026_04        0
           inundation_pct    2026_05        0
inundation_intensity_mean    2021_04        0
inundation_intensity_mean    2021_05        0
inundation_intensity_mean    2021_06       67
inundation_intensity_mean    2021_07      132
inundation_intensity_mean    2021_08      103
inundation_intensity_mean    2021_09       92
inundation_intensity_mean    2021_10        0
inundation_intensity_mean    2021_11        0
inundation_intensity_mean    2021_12        0
inundation_intensity_mean    2022_01        0
inundation_intensity_mean    2022_02        0
inundation_intensity_mean    2022_03        0
inundation_intensity_mean    2022_04        0
inundation_intensity_mean    2022_05      163
inundation_intensity_mean    2022_06      171
inundation_intensity_mean    2022_07      171
inundation_intensity_mean    2022_08        0
inundation_intensity_mean    2022_09        0
inundation_intensity_mean    2022_10        0
inundation_intensity_mean    2022_11        0
inundation_intensity_mean    2022_12        0
inundation_intensity_mean    2023_01        0
inundation_intensity_mean    2023_02        0
inundation_intensity_mean    2023_03        0
inundation_intensity_mean    2023_04        0
inundation_intensity_mean    2023_05        0
inundation_intensity_mean    2023_06      158
inundation_intensity_mean    2023_07      108
inundation_intensity_mean    2023_08       80
inundation_intensity_mean    2023_09        0
inundation_intensity_mean    2023_10        0
inundation_intensity_mean    2023_11        0
inundation_intensity_mean    2023_12        0
inundation_intensity_mean    2024_01        0
inundation_intensity_mean    2024_02        0
inundation_intensity_mean    2024_03        0
inundation_intensity_mean    2024_04        0
inundation_intensity_mean    2024_05       25
inundation_intensity_mean    2024_06      140
inundation_intensity_mean    2024_07      175
inundation_intensity_mean    2024_08       86
inundation_intensity_mean    2024_09        0
inundation_intensity_mean    2024_10        0
inundation_intensity_mean    2024_11        0
inundation_intensity_mean    2024_12        0
inundation_intensity_mean    2025_01        0
inundation_intensity_mean    2025_02        0
inundation_intensity_mean    2025_03        0
inundation_intensity_mean    2025_04        0
inundation_intensity_mean    2025_05        0
inundation_intensity_mean    2025_06      167
inundation_intensity_mean    2025_07      135
inundation_intensity_mean    2025_08       40
inundation_intensity_mean    2025_09       74
inundation_intensity_mean    2025_10        0
inundation_intensity_mean    2025_11        0
inundation_intensity_mean    2025_12        0
inundation_intensity_mean    2026_01        0
inundation_intensity_mean    2026_02        0
inundation_intensity_mean    2026_03        0
inundation_intensity_mean    2026_04        0
inundation_intensity_mean    2026_05        0
          riverlevel_mean    2021_04       50
          riverlevel_mean    2021_05       50
          riverlevel_mean    2021_06       50
          riverlevel_mean    2021_07       50
          riverlevel_mean    2021_08       50
          riverlevel_mean    2021_09       50
          riverlevel_mean    2021_10       50
          riverlevel_mean    2021_11       50
          riverlevel_mean    2021_12       50
          riverlevel_mean    2022_01       50
          riverlevel_mean    2022_02       50
          riverlevel_mean    2022_03       50
          riverlevel_mean    2022_04       50
          riverlevel_mean    2022_05       50
          riverlevel_mean    2022_06       50
          riverlevel_mean    2022_07       50
          riverlevel_mean    2022_08       50
          riverlevel_mean    2022_09       50
          riverlevel_mean    2022_10       50
          riverlevel_mean    2022_11       50
          riverlevel_mean    2022_12       49
          riverlevel_mean    2023_01       49
          riverlevel_mean    2023_02       50
          riverlevel_mean    2023_03       50
          riverlevel_mean    2023_04       50
          riverlevel_mean    2023_05       50
          riverlevel_mean    2023_06       50
          riverlevel_mean    2023_07       50
          riverlevel_mean    2023_08       50
          riverlevel_mean    2023_09       50
          riverlevel_mean    2023_10       50
          riverlevel_mean    2023_11       50
          riverlevel_mean    2023_12       50
          riverlevel_mean    2024_01       50
          riverlevel_mean    2024_02       50
          riverlevel_mean    2024_03       50
          riverlevel_mean    2024_04       50
          riverlevel_mean    2024_05       50
          riverlevel_mean    2024_06        0
          riverlevel_mean    2024_07        0
          riverlevel_mean    2024_08        0
          riverlevel_mean    2024_09        0
          riverlevel_mean    2024_10        0
          riverlevel_mean    2024_11        0
          riverlevel_mean    2024_12        0
          riverlevel_mean    2025_01        0
          riverlevel_mean    2025_02        0
          riverlevel_mean    2025_03        0
          riverlevel_mean    2025_04        0
          riverlevel_mean    2025_05        0
          riverlevel_mean    2025_06        0
          riverlevel_mean    2025_07        0
          riverlevel_mean    2025_08        0
          riverlevel_mean    2025_09        0
          riverlevel_mean    2025_10        0
          riverlevel_mean    2025_11        0
          riverlevel_mean    2025_12        0
          riverlevel_mean    2026_01        0
          riverlevel_mean    2026_02        0
          riverlevel_mean    2026_03        0
          riverlevel_mean    2026_04        0

In [65]:


# Candidate variables for predicting NEXT month's impact.
# Final inclusion requires prediction-time availability and leakage screening.
# because they describe the current environmental/spatial state.

prediction_features = [
    # -------------------------
    # CURRENT ENVIRONMENT
    # -------------------------
    'max_rain',
    'mean_rain',
    'sum_rain',

    'mean_ndvi',
    'mean_ndbi',

    'inundation_pct',
    'inundation_intensity_mean',
    'inundation_intensity_mean_nonzero',
    'inundation_intensity_sum',

    'riverlevel_mean',
    'riverlevel_min',
    'riverlevel_max',

    'water',
    'trees',
    'flooded_vegetation',
    'crops',
    'built_area',
    'bare_ground',
    'clouds',
    'rangeland',

    # -------------------------
    # EXPOSURE / VULNERABILITY
    # -------------------------
    'sum_population',
    'sum_aged_population',
    'sum_young_population',
    'mean_sex_ratio',
    'total_hhd',

    'net_sown_area_in_hac',

    'schools_count',
    'health_centres_count',

    'road_length',
    'rail_length',
    'rail_count',

    'distance_from_river',
    'drainage_density',

    'elevation_mean',
    'slope_mean',
    'mean_cn'
]

# Current impact is retained as a candidate historical predictor.
# It must be explicitly lagged when constructing the one-month-ahead dataset.
prediction_features += ['impact']


print("=" * 70)
print("PREDICTION FEATURE SET")
print("=" * 70)

for i, col in enumerate(prediction_features, 1):
    print(f"{i:2d}. {col}")

print("\nTotal candidate prediction features:", len(prediction_features))

======================================================================
PREDICTION FEATURE SET
======================================================================
 1. max_rain
 2. mean_rain
 3. sum_rain
 4. mean_ndvi
 5. mean_ndbi
 6. inundation_pct
 7. inundation_intensity_mean
 8. inundation_intensity_mean_nonzero
 9. inundation_intensity_sum
10. riverlevel_mean
11. riverlevel_min
12. riverlevel_max
13. water
14. trees
15. flooded_vegetation
16. crops
17. built_area
18. bare_ground
19. clouds
20. rangeland
21. sum_population
22. sum_aged_population
23. sum_young_population
24. mean_sex_ratio
25. total_hhd
26. net_sown_area_in_hac
27. schools_count
28. health_centres_count
29. road_length
30. rail_length
31. rail_count
32. distance_from_river
33. drainage_density
34. elevation_mean
35. slope_mean
36. mean_cn
37. impact

Total candidate prediction features: 37

## 5. Prediction Feature Selection

The candidate prediction variables are evaluated based on:

1. Availability at the time of prediction
2. Risk of target leakage
3. Whether the variable represents a predictor or a consequence/response to flooding
4. Data coverage and sparsity
5. Relevance to one-month-ahead flood-impact prediction

The objective is to identify a defensible feature set for the subsequent model-training stage.

In [66]:

availability = []

for col in prediction_features:
    if col in df.columns:
        nonzero = (df[col].fillna(0) != 0).sum()
        missing = df[col].isna().sum()
        unique = df[col].nunique(dropna=True)

        availability.append({
            'variable': col,
            'nonzero': nonzero,
            'missing': missing,
            'unique': unique,
            'coverage_pct': round(
                100 * (len(df) - missing) / len(df), 2
            )
        })
    else:
        availability.append({
            'variable': col,
            'nonzero': 'NOT FOUND',
            'missing': 'NOT FOUND',
            'unique': 'NOT FOUND',
            'coverage_pct': 'NOT FOUND'
        })

availability_df = pd.DataFrame(availability)

display(availability_df)

                             variable  nonzero  missing  unique  coverage_pct
0                            max_rain    10370        0    4309         100.0
1                           mean_rain    10370        0   10030         100.0
2                            sum_rain    10370        0   10370         100.0
3                           mean_ndvi    11160        0    3802         100.0
4                           mean_ndbi    11160        0    3622         100.0
5                      inundation_pct     2087        0    2088         100.0
6           inundation_intensity_mean     2087        0    2087         100.0
7   inundation_intensity_mean_nonzero     2087        0    1290         100.0
8            inundation_intensity_sum     2087        0    2015         100.0
9                     riverlevel_mean     1898        0    1899         100.0
10                     riverlevel_min     1881        0    1552         100.0
11                     riverlevel_max     1898        0    1633         100.0
12                              water     5907        0     538         100.0
13                              trees     5940        0     541         100.0
14                 flooded_vegetation     3906        0     356         100.0
15                              crops     5940        0     541         100.0
16                         built_area     5940        0     541         100.0
17                        bare_ground     4947        0     451         100.0
18                             clouds       93        0      11         100.0
19                          rangeland     5673        0     517         100.0
20                     sum_population    11160        0    1080         100.0
21                sum_aged_population    11160        0    1080         100.0
22               sum_young_population    11160        0    1080         100.0
23                     mean_sex_ratio    11160        0    1080         100.0
24                          total_hhd    10912        0     177         100.0
25               net_sown_area_in_hac    11160        0     178         100.0
26                      schools_count    11160        0     156         100.0
27               health_centres_count    11160        0      49         100.0
28                        road_length    11160        0     180         100.0
29                        rail_length     7316        0     119         100.0
30                         rail_count     7316        0      31         100.0
31                distance_from_river    11160        0     180         100.0
32                   drainage_density    11160        0     143         100.0
33                     elevation_mean    11160        0     180         100.0
34                         slope_mean    11160        0     180         100.0
35                            mean_cn    11160        0     180         100.0
36                             impact      877        0       2         100.0

In [67]:


df_pred = df.copy()

# Convert YYYY_MM into an actual date
df_pred['date'] = pd.to_datetime(
    df_pred['timeperiod'].astype(str),
    format='%Y_%m'
)

# Sort by Revenue Circle and time
df_pred = df_pred.sort_values(
    ['object_id', 'date']
).reset_index(drop=True)

# ------------------------------------------------------------
# NEXT MONTH'S IMPACT
# ------------------------------------------------------------

df_pred['next_month_impact'] = (
    df_pred
    .groupby('object_id')['impact']
    .shift(-1)
)

# Next month's date
df_pred['next_month_date'] = (
    df_pred
    .groupby('object_id')['date']
    .shift(-1)
)

# ------------------------------------------------------------
# VERIFY THAT IT IS ACTUALLY THE IMMEDIATE NEXT MONTH
# ------------------------------------------------------------

month_difference = (
    (df_pred['next_month_date'].dt.year -
     df_pred['date'].dt.year) * 12
    +
    (df_pred['next_month_date'].dt.month -
     df_pred['date'].dt.month)
)

df_pred['valid_next_month'] = (
    month_difference == 1
)

# Keep only genuine one-month-ahead observations
df_pred = df_pred[
    df_pred['valid_next_month']
].copy()

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("=" * 70)
print("ONE-MONTH-AHEAD PREDICTION DATASET")
print("=" * 70)

print("Total observations:", len(df_pred))

print(
    "Revenue Circles:",
    df_pred['object_id'].nunique()
)

print(
    "Time range:",
    df_pred['date'].min(),
    "→",
    df_pred['date'].max()
)

print("\nNext-month impact distribution:")
print(
    df_pred['next_month_impact']
    .value_counts()
    .sort_index()
)

print("\nNext-month impact proportion:")
print(
    df_pred['next_month_impact'].mean()
)

print("\nValid next-month observations:")
print(
    df_pred['valid_next_month'].value_counts()
)

======================================================================
ONE-MONTH-AHEAD PREDICTION DATASET
======================================================================
Total observations: 10980
Revenue Circles: 180
Time range: 2021-04-01 00:00:00 → 2026-04-01 00:00:00

Next-month impact distribution:
next_month_impact
0.0    10103
1.0      877
Name: count, dtype: int64

Next-month impact proportion:
0.07987249544626594

Valid next-month observations:
valid_next_month
True    10980
Name: count, dtype: int64

In [68]:

# Initial feature-selection screening
# Each candidate is classified using prediction-time availability,
# leakage risk, data coverage, and relevance to the prediction task.

feature_screening = {

    # -------------------------
    # HAZARD / ENVIRONMENT
    # -------------------------
    "max_rain": ("KEEP", "Direct rainfall indicator; broadly available."),
    "mean_rain": ("KEEP", "Direct rainfall indicator; broadly available."),
    "sum_rain": ("KEEP", "Direct cumulative rainfall indicator; broadly available."),

    "mean_ndvi": ("CHECK TIMING", "Useful environmental predictor; verify imagery timing."),
    "mean_ndbi": ("CHECK TIMING", "Useful built-environment indicator; verify imagery timing."),

    "inundation_pct": (
        "SECONDARY",
        "Represents current flood state; exclude from strict early-warning baseline."
    ),
    "inundation_intensity_mean": (
        "SECONDARY",
        "Represents current flood state; exclude from strict early-warning baseline."
    ),
    "inundation_intensity_mean_nonzero": (
        "SECONDARY",
        "Represents current flood state; exclude from strict early-warning baseline."
    ),
    "inundation_intensity_sum": (
        "SECONDARY",
        "Represents current flood state; exclude from strict early-warning baseline."
    ),

    "riverlevel_mean": (
        "CHECK TIMING",
        "Potentially strong hazard predictor; verify that observations are known by prediction cutoff."
    ),
    "riverlevel_min": (
        "CHECK TIMING",
        "Potentially strong hazard predictor; verify prediction-time availability."
    ),
    "riverlevel_max": (
        "CHECK TIMING",
        "Potentially strong hazard predictor; verify prediction-time availability."
    ),

    "water": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),
    "trees": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),
    "flooded_vegetation": (
        "SECONDARY",
        "Flood-state indicator; exclude from strict early-warning baseline."
    ),
    "crops": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),
    "built_area": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),
    "bare_ground": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),
    "clouds": (
        "REMOVE",
        "Extremely sparse: only 93 nonzero observations."
    ),
    "rangeland": ("CHECK TIMING", "Land/environment characteristic; verify acquisition timing."),

    # -------------------------
    # EXPOSURE / VULNERABILITY
    # -------------------------
    "sum_population": ("KEEP", "Population exposure; complete coverage."),
    "sum_aged_population": ("KEEP", "Population vulnerability; complete coverage."),
    "sum_young_population": ("KEEP", "Population vulnerability; complete coverage."),
    "mean_sex_ratio": ("KEEP", "Population characteristic; complete coverage."),
    "total_hhd": ("KEEP", "Household exposure; complete coverage."),

    "net_sown_area_in_hac": (
        "KEEP",
        "Agricultural exposure; complete coverage."
    ),

    "schools_count": ("KEEP", "Critical infrastructure exposure; complete coverage."),
    "health_centres_count": (
        "KEEP",
        "Critical infrastructure exposure; complete coverage."
    ),
    "road_length": ("KEEP", "Transport infrastructure exposure; complete coverage."),

    "rail_length": (
        "CHECK ZERO MEANING",
        "Zero values may represent absence of rail infrastructure; verify interpretation."
    ),
    "rail_count": (
        "CHECK ZERO MEANING",
        "Zero values may represent absence of rail infrastructure; verify interpretation."
    ),

    # -------------------------
    # PHYSICAL GEOGRAPHY
    # -------------------------
    "distance_from_river": ("KEEP", "Flood susceptibility indicator; complete coverage."),
    "drainage_density": ("KEEP", "Hydrological/geographic characteristic; complete coverage."),
    "elevation_mean": ("KEEP", "Topographic characteristic; complete coverage."),
    "slope_mean": ("KEEP", "Topographic characteristic; complete coverage."),
    "mean_cn": ("KEEP", "Runoff-related physical characteristic; complete coverage."),

    # -------------------------
    # HISTORICAL IMPACT
    # -------------------------
    "impact": (
        "KEEP AS LAGGED FEATURE",
        "Previous/current-period impact can predict next-month impact; must remain temporally aligned."
    )
}


feature_selection_df = pd.DataFrame(
    [
        {
            "variable": variable,
            "decision": decision,
            "reason": reason
        }
        for variable, (decision, reason) in feature_screening.items()
    ]
)

print("=" * 80)
print("INITIAL FEATURE SELECTION SCREENING")
print("=" * 80)

display(feature_selection_df)

print("\nDecision counts:")
print(feature_selection_df["decision"].value_counts())

================================================================================
INITIAL FEATURE SELECTION SCREENING
================================================================================

,variable,decision,reason
0,max_rain,KEEP,Direct rainfall indicator; broadly available.
1,mean_rain,KEEP,Direct rainfall indicator; broadly available.
2,sum_rain,KEEP,Direct cumulative rainfall indicator; broadly ...
3,mean_ndvi,CHECK TIMING,Useful environmental predictor; verify imagery...
4,mean_ndbi,CHECK TIMING,Useful built-environment indicator; verify ima...
5,inundation_pct,SECONDARY,Represents current flood state; exclude from s...
6,inundation_intensity_mean,SECONDARY,Represents current flood state; exclude from s...
7,inundation_intensity_mean_nonzero,SECONDARY,Represents current flood state; exclude from s...
8,inundation_intensity_sum,SECONDARY,Represents current flood state; exclude from s...
9,riverlevel_mean,CHECK TIMING,Potentially strong hazard predictor; verify th...
10,riverlevel_min,CHECK TIMING,Potentially strong hazard predictor; verify pr...
11,riverlevel_max,CHECK TIMING,Potentially strong hazard predictor; verify pr...
12,water,CHECK TIMING,Land/environment characteristic; verify acquis...
13,trees,CHECK TIMING,Land/environment characteristic; verify acquis...
14,flooded_vegetation,SECONDARY,Flood-state indicator; exclude from strict ear...
15,crops,CHECK TIMING,Land/environment characteristic; verify acquis...
16,built_area,CHECK TIMING,Land/environment characteristic; verify acquis...
17,bare_ground,CHECK TIMING,Land/environment characteristic; verify acquis...
18,clouds,REMOVE,Extremely sparse: only 93 nonzero observations.
19,rangeland,CHECK TIMING,Land/environment characteristic; verify acquis...
20,sum_population,KEEP,Population exposure; complete coverage.
21,sum_aged_population,KEEP,Population vulnerability; complete coverage.
22,sum_young_population,KEEP,Population vulnerability; complete coverage.
23,mean_sex_ratio,KEEP,Population characteristic; complete coverage.
24,total_hhd,KEEP,Household exposure; complete coverage.
25,net_sown_area_in_hac,KEEP,Agricultural exposure; complete coverage.
26,schools_count,KEEP,Critical infrastructure exposure; complete cov...
27,health_centres_count,KEEP,Critical infrastructure exposure; complete cov...
28,road_length,KEEP,Transport infrastructure exposure; complete co...
29,rail_length,CHECK ZERO MEANING,Zero values may represent absence of rail infr...
30,rail_count,CHECK ZERO MEANING,Zero values may represent absence of rail infr...
31,distance_from_river,KEEP,Flood susceptibility indicator; complete cover...
32,drainage_density,KEEP,Hydrological/geographic characteristic; comple...
33,elevation_mean,KEEP,Topographic characteristic; complete coverage.
34,slope_mean,KEEP,Topographic characteristic; complete coverage.
35,mean_cn,KEEP,Runoff-related physical characteristic; comple...
36,impact,KEEP AS LAGGED FEATURE,Previous/current-period impact can predict nex...

Decision counts:
decision
KEEP                      17
CHECK TIMING              11
SECONDARY                  5
CHECK ZERO MEANING         2
REMOVE                     1
KEEP AS LAGGED FEATURE     1
Name: count, dtype: int64

In [69]:
# Construct the strict early-warning baseline feature set

baseline_features = [
    # Rainfall
    "max_rain",
    "mean_rain",
    "sum_rain",

    # Population / exposure
    "sum_population",
    "sum_aged_population",
    "sum_young_population",
    "mean_sex_ratio",
    "total_hhd",
    "net_sown_area_in_hac",

    # Infrastructure
    "schools_count",
    "health_centres_count",
    "road_length",

    # Physical geography
    "distance_from_river",
    "drainage_density",
    "elevation_mean",
    "slope_mean",
    "mean_cn",

    # Historical impact
    "impact"
]

print("=" * 80)
print("STRICT EARLY-WARNING BASELINE FEATURES")
print("=" * 80)

print(f"\nNumber of baseline features: {len(baseline_features)}")

for i, feature in enumerate(baseline_features, start=1):
    print(f"{i:2}. {feature}")

================================================================================
STRICT EARLY-WARNING BASELINE FEATURES
================================================================================

Number of baseline features: 18
 1. max_rain
 2. mean_rain
 3. sum_rain
 4. sum_population
 5. sum_aged_population
 6. sum_young_population
 7. mean_sex_ratio
 8. total_hhd
 9. net_sown_area_in_hac
10. schools_count
11. health_centres_count
12. road_length
13. distance_from_river
14. drainage_density
15. elevation_mean
16. slope_mean
17. mean_cn
18. impact

In [70]:
# Variables requiring additional validation before inclusion

review_features = [
    "mean_ndvi",
    "mean_ndbi",
    "riverlevel_mean",
    "riverlevel_min",
    "riverlevel_max",
    "water",
    "trees",
    "crops",
    "built_area",
    "bare_ground",
    "rangeland",
    "rail_length",
    "rail_count"
]

print("=" * 80)
print("FEATURES REQUIRING ADDITIONAL VALIDATION")
print("=" * 80)

print(f"\nNumber of features requiring review: {len(review_features)}")

for i, feature in enumerate(review_features, start=1):
    print(f"{i:2}. {feature}")

================================================================================
FEATURES REQUIRING ADDITIONAL VALIDATION
================================================================================

Number of features requiring review: 13
 1. mean_ndvi
 2. mean_ndbi
 3. riverlevel_mean
 4. riverlevel_min
 5. riverlevel_max
 6. water
 7. trees
 8. crops
 9. built_area
10. bare_ground
11. rangeland
12. rail_length
13. rail_count

In [71]:
# Coverage and variability check for features requiring validation

review_summary = pd.DataFrame({
    "nonzero": df[review_features].ne(0).sum(),
    "missing": df[review_features].isna().sum(),
    "unique": df[review_features].nunique(),
    "min": df[review_features].min(),
    "max": df[review_features].max(),
    "mean": df[review_features].mean()
})

review_summary["nonzero_pct"] = (
    review_summary["nonzero"] / len(df) * 100
)

review_summary = review_summary[
    ["nonzero", "nonzero_pct", "missing", "unique", "min", "max", "mean"]
].sort_values(
    by="nonzero_pct",
    ascending=True
)

print("=" * 80)
print("VALIDATION: COVERAGE AND VARIABILITY")
print("=" * 80)

display(review_summary)

================================================================================
VALIDATION: COVERAGE AND VARIABILITY
================================================================================

,nonzero,nonzero_pct,missing,unique,min,max,mean
riverlevel_min,1881,16.854839,0,1552,0.000000,144.310000,9.606417
riverlevel_mean,1898,17.007168,0,1899,0.000000,508.346495,11.225171
riverlevel_max,1898,17.007168,0,1633,0.000000,75030.000000,20.315696
bare_ground,4947,44.327957,0,451,0.000000,33.319956,2.044138
rangeland,5673,50.833333,0,517,0.000000,22.223732,1.934040
water,5907,52.930108,0,538,0.000000,29.943675,2.728140
trees,5940,53.225806,0,541,0.000000,96.011204,12.651232
crops,5940,53.225806,0,541,0.000000,81.197631,24.000577
built_area,5940,53.225806,0,541,0.000000,87.207774,9.739803
rail_length,7316,65.555556,0,119,0.000000,89846.699322,15058.706132
rail_count,7316,65.555556,0,31,0.000000,114.000000,8.250000
mean_ndvi,11160,100.000000,0,3802,-0.098735,0.887988,0.472349
mean_ndbi,11160,100.000000,0,3622,-0.579713,0.128507,-0.123280

In [72]:
# Check the meaning of zero values in variables requiring validation

zero_check = pd.DataFrame({
    "zero_count": (df[review_features] == 0).sum(),
    "zero_percentage": (df[review_features] == 0).mean() * 100,
    "nonzero_count": (df[review_features] != 0).sum(),
    "missing_count": df[review_features].isna().sum()
})

zero_check = zero_check.sort_values(
    by="zero_percentage",
    ascending=False
)

print("=" * 80)
print("ZERO-VALUE ANALYSIS")
print("=" * 80)

display(zero_check)

================================================================================
ZERO-VALUE ANALYSIS
================================================================================

                 zero_count  zero_percentage  nonzero_count  missing_count
riverlevel_min         9279        83.145161           1881              0
riverlevel_max         9262        82.992832           1898              0
riverlevel_mean        9262        82.992832           1898              0
bare_ground            6213        55.672043           4947              0
rangeland              5487        49.166667           5673              0
water                  5253        47.069892           5907              0
crops                  5220        46.774194           5940              0
built_area             5220        46.774194           5940              0
trees                  5220        46.774194           5940              0
rail_length            3844        34.444444           7316              0
rail_count             3844        34.444444           7316              0
mean_ndbi                 0         0.000000          11160              0
mean_ndvi                 0         0.000000          11160              0

In [73]:
# Examine the temporal and spatial distribution of river-level observations

riverlevel_features = [
    "riverlevel_mean",
    "riverlevel_min",
    "riverlevel_max"
]

print("=" * 80)
print("RIVER-LEVEL OBSERVATION DISTRIBUTION")
print("=" * 80)

print("\nNonzero observations by year:")

river_nonzero = df[df["riverlevel_mean"] > 0].copy()

river_nonzero["year"] = (
    pd.to_datetime(river_nonzero["timeperiod"], errors="coerce")
    .dt.year
)

display(
    river_nonzero.groupby("year")[riverlevel_features]
    .agg(["count", "mean"])
)

print("\nNonzero observations by month:")

river_nonzero["month"] = (
    pd.to_datetime(river_nonzero["timeperiod"], errors="coerce")
    .dt.month
)

display(
    river_nonzero.groupby("month")[riverlevel_features]
    .count()
)

================================================================================
RIVER-LEVEL OBSERVATION DISTRIBUTION
================================================================================

Nonzero observations by year:

/tmp/ipykernel_3272/1318118331.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(river_nonzero["timeperiod"], errors="coerce")

Empty DataFrame
Columns: [(riverlevel_mean, count), (riverlevel_mean, mean), (riverlevel_min, count), (riverlevel_min, mean), (riverlevel_max, count), (riverlevel_max, mean)]
Index: []

Nonzero observations by month:

/tmp/ipykernel_3272/1318118331.py:30: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(river_nonzero["timeperiod"], errors="coerce")

Empty DataFrame
Columns: [riverlevel_mean, riverlevel_min, riverlevel_max]
Index: []

In [74]:
# Inspect the actual timeperiod format

print("=" * 80)
print("TIMEPERIOD FORMAT CHECK")
print("=" * 80)

print("\nSample timeperiod values:")
display(df["timeperiod"].head(20))

print("\nData type:")
print(df["timeperiod"].dtype)

print("\nNumber of unique timeperiod values:")
print(df["timeperiod"].nunique())

print("\nSample unique values:")
print(df["timeperiod"].dropna().unique()[:20])

================================================================================
TIMEPERIOD FORMAT CHECK
================================================================================

Sample timeperiod values:

0     2021_04
1     2021_05
2     2021_06
3     2021_07
4     2021_08
5     2021_09
6     2021_10
7     2021_11
8     2021_12
9     2022_01
10    2022_02
11    2022_03
12    2022_04
13    2022_05
14    2022_06
15    2022_07
16    2022_08
17    2022_09
18    2022_10
19    2022_11
Name: timeperiod, dtype: object

Data type:
object

Number of unique timeperiod values:
62

Sample unique values:
['2021_04' '2021_05' '2021_06' '2021_07' '2021_08' '2021_09' '2021_10'
 '2021_11' '2021_12' '2022_01' '2022_02' '2022_03' '2022_04' '2022_05'
 '2022_06' '2022_07' '2022_08' '2022_09' '2022_10' '2022_11']

In [75]:
# Final feature-selection decision based on existing EDA evidence

final_feature_decisions = {

    # Strongly supported predictors
    "max_rain": "KEEP",
    "mean_rain": "KEEP",
    "sum_rain": "KEEP",

    "sum_population": "KEEP",
    "sum_aged_population": "KEEP",
    "sum_young_population": "KEEP",
    "mean_sex_ratio": "KEEP",
    "total_hhd": "KEEP",
    "net_sown_area_in_hac": "KEEP",

    "schools_count": "KEEP",
    "health_centres_count": "KEEP",
    "road_length": "KEEP",

    "distance_from_river": "KEEP",
    "drainage_density": "KEEP",
    "elevation_mean": "KEEP",
    "slope_mean": "KEEP",
    "mean_cn": "KEEP",

    # Strong temporal predictor
    "impact": "KEEP AS LAGGED FEATURE",

    # Candidate environmental variables
    "mean_ndvi": "REVIEW TIMING",
    "mean_ndbi": "REVIEW TIMING",
    "water": "REVIEW TIMING",
    "trees": "REVIEW TIMING",
    "crops": "REVIEW TIMING",
    "built_area": "REVIEW TIMING",
    "bare_ground": "REVIEW TIMING",
    "rangeland": "REVIEW TIMING",

    # Infrastructure variables with substantial zero values
    "rail_length": "REVIEW ZERO MEANING",
    "rail_count": "REVIEW ZERO MEANING",

    # River-level data has incomplete temporal availability
    "riverlevel_mean": "EXCLUDE FROM BASELINE",
    "riverlevel_min": "EXCLUDE FROM BASELINE",
    "riverlevel_max": "EXCLUDE FROM BASELINE",

    # Current flood-state variables
    "inundation_pct": "SECONDARY MODEL",
    "inundation_intensity_mean": "SECONDARY MODEL",
    "inundation_intensity_mean_nonzero": "SECONDARY MODEL",
    "inundation_intensity_sum": "SECONDARY MODEL",
    "flooded_vegetation": "SECONDARY MODEL",

    # Extremely sparse
    "clouds": "EXCLUDE"
}


final_feature_decisions_df = pd.DataFrame(
    [
        {
            "variable": variable,
            "decision": decision
        }
        for variable, decision in final_feature_decisions.items()
    ]
)

print("=" * 80)
print("FINAL FEATURE-SELECTION SCREENING")
print("=" * 80)

display(final_feature_decisions_df)

print("\nDecision summary:")
print(final_feature_decisions_df["decision"].value_counts())

================================================================================
FINAL FEATURE-SELECTION SCREENING
================================================================================

                             variable                decision
0                            max_rain                    KEEP
1                           mean_rain                    KEEP
2                            sum_rain                    KEEP
3                      sum_population                    KEEP
4                 sum_aged_population                    KEEP
5                sum_young_population                    KEEP
6                      mean_sex_ratio                    KEEP
7                           total_hhd                    KEEP
8                net_sown_area_in_hac                    KEEP
9                       schools_count                    KEEP
10               health_centres_count                    KEEP
11                        road_length                    KEEP
12                distance_from_river                    KEEP
13                   drainage_density                    KEEP
14                     elevation_mean                    KEEP
15                         slope_mean                    KEEP
16                            mean_cn                    KEEP
17                             impact  KEEP AS LAGGED FEATURE
18                          mean_ndvi           REVIEW TIMING
19                          mean_ndbi           REVIEW TIMING
20                              water           REVIEW TIMING
21                              trees           REVIEW TIMING
22                              crops           REVIEW TIMING
23                         built_area           REVIEW TIMING
24                        bare_ground           REVIEW TIMING
25                          rangeland           REVIEW TIMING
26                        rail_length     REVIEW ZERO MEANING
27                         rail_count     REVIEW ZERO MEANING
28                    riverlevel_mean   EXCLUDE FROM BASELINE
29                     riverlevel_min   EXCLUDE FROM BASELINE
30                     riverlevel_max   EXCLUDE FROM BASELINE
31                     inundation_pct         SECONDARY MODEL
32          inundation_intensity_mean         SECONDARY MODEL
33  inundation_intensity_mean_nonzero         SECONDARY MODEL
34           inundation_intensity_sum         SECONDARY MODEL
35                 flooded_vegetation         SECONDARY MODEL
36                             clouds                 EXCLUDE

Decision summary:
decision
KEEP                      17
REVIEW TIMING              8
SECONDARY MODEL            5
EXCLUDE FROM BASELINE      3
REVIEW ZERO MEANING        2
KEEP AS LAGGED FEATURE     1
EXCLUDE                    1
Name: count, dtype: int64

In [76]:
# Features requiring source-level validation before final inclusion

unresolved_features = [
    "mean_ndvi",
    "mean_ndbi",
    "water",
    "trees",
    "crops",
    "built_area",
    "bare_ground",
    "rangeland",
    "rail_length",
    "rail_count"
]

unresolved_df = pd.DataFrame({
    "variable": unresolved_features,
    "status": "SOURCE VALIDATION REQUIRED",
    "reason": [
        "Monthly environmental variable; acquisition/availability cutoff must be confirmed.",
        "Monthly environmental variable; acquisition/availability cutoff must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Land-cover variable; source timing must be confirmed.",
        "Zero may represent genuine absence of railway; source definition must be confirmed.",
        "Zero may represent genuine absence of railway; source definition must be confirmed."
    ]
})

print("=" * 80)
print("FEATURES REQUIRING SOURCE-LEVEL VALIDATION")
print("=" * 80)

display(unresolved_df)

================================================================================
FEATURES REQUIRING SOURCE-LEVEL VALIDATION
================================================================================

,variable,status,reason
0,mean_ndvi,SOURCE VALIDATION REQUIRED,Monthly environmental variable; acquisition/av...
1,mean_ndbi,SOURCE VALIDATION REQUIRED,Monthly environmental variable; acquisition/av...
2,water,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
3,trees,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
4,crops,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
5,built_area,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
6,bare_ground,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
7,rangeland,SOURCE VALIDATION REQUIRED,Land-cover variable; source timing must be con...
8,rail_length,SOURCE VALIDATION REQUIRED,Zero may represent genuine absence of railway;...
9,rail_count,SOURCE VALIDATION REQUIRED,Zero may represent genuine absence of railway;...

In [77]:
# Source-level validation of remaining candidate features

source_validation_decisions = {

    "mean_ndvi": (
        "KEEP",
        "Monthly Sentinel-2-derived NDVI per Revenue Circle; documented as an IDS-DRR model input."
    ),

    "mean_ndbi": (
        "KEEP",
        "Monthly Sentinel-2-derived NDBI per Revenue Circle; documented as an IDS-DRR model input."
    ),

    "water": (
        "TIMING UNCONFIRMED",
        "Land-cover variable; source documentation does not establish acquisition timing relative to prediction cutoff."
    ),

    "trees": (
        "TIMING UNCONFIRMED",
        "Land-cover variable; source documentation does not establish acquisition timing relative to prediction cutoff."
    ),

    "crops": (
        "TIMING UNCONFIRMED",
        "Land-cover variable; source documentation does not establish acquisition timing relative to prediction cutoff."
    ),

    "built_area": (
        "TIMING UNCONFIRMED",
        "Sentinel-2-derived built-environment variable; acquisition timing relative to prediction cutoff is not established."
    ),

    "bare_ground": (
        "TIMING UNCONFIRMED",
        "Land-cover variable; source documentation does not establish acquisition timing relative to prediction cutoff."
    ),

    "rangeland": (
        "TIMING UNCONFIRMED",
        "Land-cover variable; source documentation does not establish acquisition timing relative to prediction cutoff."
    ),

    "rail_length": (
        "ZERO MEANING UNCONFIRMED",
        "Zero values are common, but source documentation does not establish whether zero means genuine absence or unavailable data."
    ),

    "rail_count": (
        "ZERO MEANING UNCONFIRMED",
        "Zero values are common, but source documentation does not establish whether zero means genuine absence or unavailable data."
    )
}


source_validation_df = pd.DataFrame(
    [
        {
            "variable": variable,
            "decision": decision,
            "reason": reason
        }
        for variable, (decision, reason) in source_validation_decisions.items()
    ]
)

print("=" * 80)
print("SOURCE-LEVEL FEATURE VALIDATION")
print("=" * 80)

display(source_validation_df)

print("\nDecision summary:")
print(source_validation_df["decision"].value_counts())

================================================================================
SOURCE-LEVEL FEATURE VALIDATION
================================================================================

,variable,decision,reason
0,mean_ndvi,KEEP,Monthly Sentinel-2-derived NDVI per Revenue Ci...
1,mean_ndbi,KEEP,Monthly Sentinel-2-derived NDBI per Revenue Ci...
2,water,TIMING UNCONFIRMED,Land-cover variable; source documentation does...
3,trees,TIMING UNCONFIRMED,Land-cover variable; source documentation does...
4,crops,TIMING UNCONFIRMED,Land-cover variable; source documentation does...
5,built_area,TIMING UNCONFIRMED,Sentinel-2-derived built-environment variable;...
6,bare_ground,TIMING UNCONFIRMED,Land-cover variable; source documentation does...
7,rangeland,TIMING UNCONFIRMED,Land-cover variable; source documentation does...
8,rail_length,ZERO MEANING UNCONFIRMED,"Zero values are common, but source documentati..."
9,rail_count,ZERO MEANING UNCONFIRMED,"Zero values are common, but source documentati..."

Decision summary:
decision
TIMING UNCONFIRMED          6
KEEP                        2
ZERO MEANING UNCONFIRMED    2
Name: count, dtype: int64

In [78]:
# Construct the validated baseline feature set

baseline_features = [
    # Rainfall
    "max_rain",
    "mean_rain",
    "sum_rain",

    # Environmental
    "mean_ndvi",
    "mean_ndbi",

    # Population / exposure
    "sum_population",
    "sum_aged_population",
    "sum_young_population",
    "mean_sex_ratio",
    "total_hhd",
    "net_sown_area_in_hac",

    # Infrastructure
    "schools_count",
    "health_centres_count",
    "road_length",

    # Physical geography
    "distance_from_river",
    "drainage_density",
    "elevation_mean",
    "slope_mean",
    "mean_cn",

    # Historical impact
    "impact"
]

print("=" * 80)
print("BASELINE FEATURE SET")
print("=" * 80)

print(f"\nNumber of baseline features: {len(baseline_features)}")

for i, feature in enumerate(baseline_features, 1):
    print(f"{i:2d}. {feature}")

# Verify that every selected feature exists
missing_features = [
    feature for feature in baseline_features
    if feature not in df.columns
]

print("\n" + "=" * 80)
print("COLUMN VALIDATION")
print("=" * 80)

if missing_features:
    print("Missing features:")
    print(missing_features)
else:
    print("All baseline features are present in the dataframe.")

# Create baseline modelling dataset
baseline_df = df[baseline_features].copy()

print("\nBaseline dataset shape:", baseline_df.shape)

print("\nMissing values in baseline features:")
print(baseline_df.isnull().sum().sum())

================================================================================
BASELINE FEATURE SET
================================================================================

Number of baseline features: 20
 1. max_rain
 2. mean_rain
 3. sum_rain
 4. mean_ndvi
 5. mean_ndbi
 6. sum_population
 7. sum_aged_population
 8. sum_young_population
 9. mean_sex_ratio
10. total_hhd
11. net_sown_area_in_hac
12. schools_count
13. health_centres_count
14. road_length
15. distance_from_river
16. drainage_density
17. elevation_mean
18. slope_mean
19. mean_cn
20. impact

================================================================================
COLUMN VALIDATION
================================================================================
All baseline features are present in the dataframe.

Baseline dataset shape: (11160, 20)

Missing values in baseline features:
0

In [79]:
print("Columns containing 'impact':")
print([col for col in df.columns if "impact" in col.lower()])

print("\nColumns containing 'target':")
print([col for col in df.columns if "target" in col.lower()])

Columns containing 'impact':
['impact']

Columns containing 'target':
[]

In [80]:
# Check how impact is currently defined and used

print("impact dtype:", df["impact"].dtype)
print("\nimpact value counts:")
print(df["impact"].value_counts(dropna=False))

print("\nRelevant time columns:")
print([col for col in df.columns if "time" in col.lower() or "year" in col.lower() or "month" in col.lower()])

impact dtype: int64

impact value counts:
impact
0    10283
1      877
Name: count, dtype: int64

Relevant time columns:
['timeperiod']

In [81]:
print("Possible geographic/entity columns:")
print([
    col for col in df.columns
    if col.lower() in [
        "revenue_ci",
        "district",
        "dtname",
        "dtcode11",
        "object_id",
        "rc_area"
    ]
])

print("\nFirst 5 rows of relevant columns:")
print(
    df[
        [col for col in [
            "timeperiod",
            "revenue_ci",
            "district",
            "dtname",
            "dtcode11",
            "object_id",
            "impact"
        ] if col in df.columns]
    ].head()
)

Possible geographic/entity columns:
['object_id', 'district', 'rc_area', 'revenue_ci', 'dtname', 'dtcode11']

First 5 rows of relevant columns:
  timeperiod       revenue_ci   district     dtname dtcode11     object_id  \
0    2021_04  Gossaigaon (Pt)  KOKRAJHAR  KOKRAJHAR   18-300  18-300-00101
1    2021_05  Gossaigaon (Pt)  KOKRAJHAR  KOKRAJHAR   18-300  18-300-00101
2    2021_06  Gossaigaon (Pt)  KOKRAJHAR  KOKRAJHAR   18-300  18-300-00101
3    2021_07  Gossaigaon (Pt)  KOKRAJHAR  KOKRAJHAR   18-300  18-300-00101
4    2021_08  Gossaigaon (Pt)  KOKRAJHAR  KOKRAJHAR   18-300  18-300-00101

   impact
0       0
1       0
2       0
3       0
4       0

In [82]:
# Create the one-month-ahead prediction target
# Target = next month's impact for the same Revenue Circle

df = df.sort_values(
    ["object_id", "timeperiod"]
).copy()

df["next_month_impact"] = (
    df.groupby("object_id")["impact"]
      .shift(-1)
)

print("=" * 80)
print("ONE-MONTH-AHEAD TARGET")
print("=" * 80)

print("\nTarget distribution:")
print(df["next_month_impact"].value_counts(dropna=False))

print("\nMissing target values:", df["next_month_impact"].isna().sum())

print("\nSample:")
print(
    df[
        ["object_id", "timeperiod", "impact", "next_month_impact"]
    ].head(10)
)

================================================================================
ONE-MONTH-AHEAD TARGET
================================================================================

Target distribution:
next_month_impact
0.0    10103
1.0      877
NaN      180
Name: count, dtype: int64

Missing target values: 180

Sample:
      object_id timeperiod  impact  next_month_impact
0  18-300-00101    2021_04       0                0.0
1  18-300-00101    2021_05       0                0.0
2  18-300-00101    2021_06       0                0.0
3  18-300-00101    2021_07       0                0.0
4  18-300-00101    2021_08       0                0.0
5  18-300-00101    2021_09       0                0.0
6  18-300-00101    2021_10       0                0.0
7  18-300-00101    2021_11       0                0.0
8  18-300-00101    2021_12       0                0.0
9  18-300-00101    2022_01       0                0.0

In [83]:
# Create the final baseline modelling dataset

model_df = df.dropna(subset=["next_month_impact"]).copy()

X_baseline = model_df[baseline_features].copy()
y = model_df["next_month_impact"].astype(int)

print("=" * 80)
print("FINAL BASELINE MODELLING DATASET")
print("=" * 80)

print("\nFeature matrix shape:", X_baseline.shape)
print("Target shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print((y.value_counts(normalize=True) * 100).round(2))

print("\nMissing values:")
print("X:", X_baseline.isnull().sum().sum())
print("y:", y.isnull().sum())

================================================================================
FINAL BASELINE MODELLING DATASET
================================================================================

Feature matrix shape: (10980, 20)
Target shape: (10980,)

Target distribution:
next_month_impact
0    10103
1      877
Name: count, dtype: int64

Target percentage:
next_month_impact
0    92.01
1     7.99
Name: proportion, dtype: float64

Missing values:
X: 0
y: 0

In [84]:
# Final structural validation of the baseline feature matrix

print("=" * 80)
print("BASELINE FEATURE MATRIX VALIDATION")
print("=" * 80)

print("\nFeature data types:")
print(X_baseline.dtypes)

print("\nNon-numeric features:")
non_numeric = X_baseline.select_dtypes(exclude="number").columns.tolist()

if non_numeric:
    print(non_numeric)
else:
    print("None — all baseline features are numeric.")

print("\nDuplicate rows in feature matrix:", X_baseline.duplicated().sum())

print("\nInfinite values:")
print(
    np.isinf(X_baseline.select_dtypes(include="number")).sum().sum()
)

================================================================================
BASELINE FEATURE MATRIX VALIDATION
================================================================================

Feature data types:
max_rain                float64
mean_rain               float64
sum_rain                float64
mean_ndvi               float64
mean_ndbi               float64
sum_population          float64
sum_aged_population     float64
sum_young_population    float64
mean_sex_ratio          float64
total_hhd               float64
net_sown_area_in_hac    float64
schools_count             int64
health_centres_count      int64
road_length             float64
distance_from_river     float64
drainage_density        float64
elevation_mean          float64
slope_mean              float64
mean_cn                 float64
impact                    int64
dtype: object

Non-numeric features:
None — all baseline features are numeric.

Duplicate rows in feature matrix: 115

Infinite values:
0

In [85]:
# Investigate duplicate feature rows
duplicate_mask = X_baseline.duplicated(keep=False)

duplicate_rows = model_df.loc[
    duplicate_mask,
    ["object_id", "timeperiod", "impact", "next_month_impact"] + baseline_features
].sort_values(["object_id", "timeperiod"])

print("=" * 80)
print("DUPLICATE FEATURE-ROW INVESTIGATION")
print("=" * 80)

print("\nNumber of duplicate feature rows:", duplicate_mask.sum())

print("\nUnique object_id + timeperiod combinations among duplicates:")
print(
    duplicate_rows[["object_id", "timeperiod"]]
    .duplicated()
    .sum()
)

print("\nSample duplicate rows:")
display(duplicate_rows.head(20))

================================================================================
DUPLICATE FEATURE-ROW INVESTIGATION
================================================================================

Number of duplicate feature rows: 229

Unique object_id + timeperiod combinations among duplicates:
0

Sample duplicate rows:

,object_id,timeperiod,impact,next_month_impact,max_rain,mean_rain,sum_rain,mean_ndvi,mean_ndbi,sum_population,...,net_sown_area_in_hac,schools_count,health_centres_count,road_length,distance_from_river,drainage_density,elevation_mean,slope_mean,mean_cn,impact
57,18-300-00101,2026_01,0,0.0,0.0,0.0,0.0,0.541936,-0.148529,325099.125000,...,32583.05000,759,49,197887.351181,1718.766638,0.000542,78.792197,84.479880,76.369986,0
58,18-300-00101,2026_02,0,0.0,0.0,0.0,0.0,0.541936,-0.148529,325099.125000,...,32583.05000,759,49,197887.351181,1718.766638,0.000542,78.792197,84.479880,76.369986,0
107,18-300-00102,2025_01,0,0.0,0.0,0.0,0.0,0.505253,-0.112197,56189.542578,...,2199.40000,328,21,42518.033888,1585.679124,0.000641,45.445305,83.955808,78.192847,0
118,18-300-00102,2025_12,0,0.0,0.0,0.0,0.0,0.505253,-0.112197,56189.542578,...,2199.40000,328,21,42518.033888,1585.679124,0.000641,45.445305,83.955808,78.192847,0
119,18-300-00102,2026_01,0,0.0,0.0,0.0,0.0,0.505253,-0.112197,56074.615625,...,2199.40000,328,21,42518.033888,1585.679124,0.000641,45.445305,83.955808,78.192847,0
120,18-300-00102,2026_02,0,0.0,0.0,0.0,0.0,0.505253,-0.112197,56074.615625,...,2199.40000,328,21,42518.033888,1585.679124,0.000641,45.445305,83.955808,78.192847,0
169,18-300-00103,2025_01,0,0.0,0.0,0.0,0.0,0.483028,-0.119742,196623.689062,...,18388.48500,475,28,155276.595114,853.552864,0.000652,52.877857,83.401306,77.810206,0
180,18-300-00103,2025_12,0,0.0,0.0,0.0,0.0,0.483028,-0.119742,196623.689062,...,18388.48500,475,28,155276.595114,853.552864,0.000652,52.877857,83.401306,77.810206,0
181,18-300-00103,2026_01,0,0.0,0.0,0.0,0.0,0.483028,-0.119742,195836.025000,...,18388.48500,475,28,155276.595114,853.552864,0.000652,52.877857,83.401306,77.810206,0
182,18-300-00103,2026_02,0,0.0,0.0,0.0,0.0,0.483028,-0.119742,195836.025000,...,18388.48500,475,28,155276.595114,853.552864,0.000652,52.877857,83.401306,77.810206,0
231,18-300-00104,2025_01,0,0.0,0.0,0.0,0.0,0.658169,-0.160708,342072.593750,...,21680.64300,717,32,271904.788324,1570.415821,0.000512,105.501320,85.523802,75.623384,0
242,18-300-00104,2025_12,0,0.0,0.0,0.0,0.0,0.658169,-0.160708,342072.593750,...,21680.64300,717,32,271904.788324,1570.415821,0.000512,105.501320,85.523802,75.623384,0
243,18-300-00104,2026_01,0,0.0,0.0,0.0,0.0,0.658169,-0.160708,342926.581250,...,21680.64300,717,32,271904.788324,1570.415821,0.000512,105.501320,85.523802,75.623384,0
244,18-300-00104,2026_02,0,0.0,0.0,0.0,0.0,0.658169,-0.160708,342926.581250,...,21680.64300,717,32,271904.788324,1570.415821,0.000512,105.501320,85.523802,75.623384,0
293,18-300-00105,2025_01,0,0.0,0.0,0.0,0.0,0.754577,-0.271814,113709.697656,...,554.41709,236,12,79080.409398,6823.791423,0.000538,46.151895,84.503484,77.143709,0
304,18-300-00105,2025_12,0,0.0,0.0,0.0,0.0,0.754577,-0.271814,113709.697656,...,554.41709,236,12,79080.409398,6823.791423,0.000538,46.151895,84.503484,77.143709,0
305,18-300-00105,2026_01,0,0.0,0.0,0.0,0.0,0.754577,-0.271814,113926.254687,...,554.41709,236,12,79080.409398,6823.791423,0.000538,46.151895,84.503484,77.143709,0
306,18-300-00105,2026_02,0,0.0,0.0,0.0,0.0,0.754577,-0.271814,113926.254687,...,554.41709,236,12,79080.409398,6823.791423,0.000538,46.151895,84.503484,77.143709,0
355,18-300-00106,2025_01,0,0.0,0.0,0.0,0.0,0.634770,-0.268971,53441.781250,...,2400.48000,103,5,43056.626034,6931.467966,0.000576,41.028218,83.680990,75.695511,0
366,18-300-00106,2025_12,0,0.0,0.0,0.0,0.0,0.634770,-0.268971,53441.781250,...,2400.48000,103,5,43056.626034,6931.467966,0.000576,41.028218,83.680990,75.695511,0

In [86]:
# Export final baseline modelling dataset for the modelling team

baseline_modeling_dataset = X_baseline.copy()
baseline_modeling_dataset["next_month_impact"] = y.values

baseline_modeling_dataset.to_csv(
    "baseline_modeling_dataset.csv",
    index=False
)

print("=" * 80)
print("BASELINE MODELLING DATASET EXPORTED")
print("=" * 80)

print("File:", "baseline_modeling_dataset.csv")
print("Shape:", baseline_modeling_dataset.shape)
print("Features:", X_baseline.shape[1])
print("Target:", "next_month_impact")

print("\nMissing values:")
print(baseline_modeling_dataset.isnull().sum().sum())

print("\nTarget distribution:")
print(baseline_modeling_dataset["next_month_impact"].value_counts())

================================================================================
BASELINE MODELLING DATASET EXPORTED
================================================================================
File: baseline_modeling_dataset.csv
Shape: (10980, 21)
Features: 20
Target: next_month_impact

Missing values:
0

Target distribution:
next_month_impact
0    10103
1      877
Name: count, dtype: int64

In [87]:
# Export baseline dataset with temporal and geographic metadata
# object_id and timeperiod are retained for validation/grouping only.
# They are NOT model features.

baseline_modeling_dataset_with_metadata = model_df[
    ["object_id", "timeperiod"] + baseline_features + ["next_month_impact"]
].copy()

baseline_modeling_dataset_with_metadata.to_csv(
    "baseline_modeling_dataset_with_metadata.csv",
    index=False
)

print("=" * 80)
print("BASELINE MODELLING DATASET WITH METADATA EXPORTED")
print("=" * 80)

print("File:", "baseline_modeling_dataset_with_metadata.csv")
print("Shape:", baseline_modeling_dataset_with_metadata.shape)

print("\nMetadata columns:")
print(["object_id", "timeperiod"])

print("\nNumber of model features:", len(baseline_features))
print("Target:", "next_month_impact")

print("\nMissing values:")
print(baseline_modeling_dataset_with_metadata.isnull().sum().sum())

print("\nFirst 5 rows:")
display(baseline_modeling_dataset_with_metadata.head())

================================================================================
BASELINE MODELLING DATASET WITH METADATA EXPORTED
================================================================================
File: baseline_modeling_dataset_with_metadata.csv
Shape: (10980, 23)

Metadata columns:
['object_id', 'timeperiod']

Number of model features: 20
Target: next_month_impact

Missing values:
0

First 5 rows:

,object_id,timeperiod,max_rain,mean_rain,sum_rain,mean_ndvi,mean_ndbi,sum_population,sum_aged_population,sum_young_population,...,schools_count,health_centres_count,road_length,distance_from_river,drainage_density,elevation_mean,slope_mean,mean_cn,impact,next_month_impact
0,18-300-00101,2021_04,0.214262,0.171746,166.249990,0.367604,0.001127,327337.78125,17667.14,34582.947,...,759,49,197887.351181,1718.766638,0.000542,78.792197,84.47988,76.369986,0,0.0
1,18-300-00101,2021_05,0.344883,0.310867,300.919378,0.483602,-0.060225,327337.78125,17667.14,34582.947,...,759,49,197887.351181,1718.766638,0.000542,78.792197,84.47988,76.369986,0,0.0
2,18-300-00101,2021_06,1.346394,0.944965,914.725700,0.567028,-0.147426,327337.78125,17667.14,34582.947,...,759,49,197887.351181,1718.766638,0.000542,78.792197,84.47988,76.369986,0,0.0
3,18-300-00101,2021_07,0.975052,0.814687,788.617197,0.662550,-0.157022,327337.78125,17667.14,34582.947,...,759,49,197887.351181,1718.766638,0.000542,78.792197,84.47988,76.369986,0,0.0
4,18-300-00101,2021_08,1.308983,0.822254,795.942200,0.662550,-0.157022,327337.78125,17667.14,34582.947,...,759,49,197887.351181,1718.766638,0.000542,78.792197,84.47988,76.369986,0,0.0